homeassistant:
  name: Home
  latitude: !secret ha_lat
  longitude: !secret ha_long
  elevation: 65
  unit_system: metric
  time_zone: Asia/Jerusalem
  allowlist_external_dirs:
    - "/media/front_door"
  media_dirs:
    front_door: "/media/front_door"
  packages: !include_dir_named packages
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret ha_base_url

sun:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  server_port: !secret ha_port
  ip_ban_enabled: true
  login_attempts_threshold: 5

python_script:

wake_on_lan:

browser_mod:
  prefix: "browser_"
  disable:
    - all

# logger:
#   default: warning
#   logs:
#     homeassistant.components.heos: debug
#     homeassistant.components.denonavr: debug
#     homeassistant.components.python_script: debug
#     homeassistant.components.python_scripts: debug
#     pydeconz: debug
#     homeassistant.components.deconz: debug
#     custom_components.ekon-local: debug
#     homeassistant.components.shell_command: debug


