homeassistant:
  name: Home
  latitude: !secret ha_lat
  longitude: !secret ha_long
  country: !secret country
  elevation: 65
  unit_system: metric
  time_zone: Asia/Jerusalem
  allowlist_external_dirs:
    - "/config/camera_snaps"
  media_dirs:
    camera_snaps: "/config/camera_snaps"
  packages: !include_dir_named packages
  customize: !include customize.yaml
  external_url: !secret ha_external_url
  internal_url: !secret ha_internal_url

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

sun:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

http:
  server_port: !secret ha_port
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies: !secret reverse_proxy_ip

python_script:

wake_on_lan:

frontend:
  themes: !include_dir_merge_named themes

recorder:
  include:
    domains:
      - switch
      - light
      - climate
      - cover
      - fan
      - device_tracker
      - lock
    entity_globs:
      - sensor.ups_*
      - binary_sensor.*door*
      - binary_sensor.*window*
      - binary_sensor.*motion*
      - binary_sensor.*presence*
      - sensor.power*
      - sensor.energy_total_next_*
      - sensor.energy_total_today_*
      - sensor.*mold*
      - sensor.*_temperature_monitor
    entities:
      - input_select.laundry_machine_status
      - binary_sensor.fridge
      - binary_sensor.freezer
      - binary_sensor.big_freezer
      - sensor.shelly_3em_channel_a_power
      - sensor.shelly_3em_channel_b_power
      - sensor.shelly_3em_channel_c_power
      - sensor.outside_climate_temperature
      - sensor.outside_climate_humidity
      - sensor.solar_system_temperature
      - sensor.front_door_lock_battery_level
      - binary_sensor.rain
      - sensor.riley_main_toggle
      - binary_sensor.internet_connection
      - binary_sensor.ubnt_interface_eth10_connected
      - binary_sensor.google_connection
      - sensor.laundry_machine_power
      - sensor.laundry_machine_energy
      - sensor.yogurt_maker_power
      - sensor.yogurt_maker_energy
      - sensor.riley_heater_power
      - sensor.riley_heater_energy
      


lovelace:
  mode: storage
  dashboards:
    lovelace-mobile:
      mode: yaml
      title: Mobile
      icon: mdi:cellphone
      show_in_sidebar: true
      filename: lovelace_portrait.yaml

    lovelace-tablet:
      mode: yaml
      title: Tablet
      icon: mdi:monitor
      show_in_sidebar: true
      filename: lovelace_landscape.yaml

    # minimalist:
    #   mode: yaml
    #   title: Minimalist
    #   icon: mdi:circle-small
    #   show_in_sidebar: true
    #   filename: ui_lovelace_minimalist/dashboard/ui-lovelace.yaml

# logger:
#   default: warning
#   logs:
#     custom_components.edgeos: debug

# logger:
#   default: warning
#   logs:
#     custom_components.webrtc: debug
#     homeassistant.components.heos: debug
#     homeassistant.components.denonavr: debug
#     homeassistant.components.python_script: debug
#     homeassistant.components.python_scripts: debug
#     pydeconz: debug
#     homeassistant.components.deconz: debug
#     custom_components.ekon-local: debug
#     homeassistant.components.shell_command: debug

