homeassistant:
  name: Home
  latitude: !secret ha_lat
  longitude: !secret ha_long
  elevation: 65
  unit_system: metric
  time_zone: Asia/Jerusalem
  allowlist_external_dirs:
    - "/media/front_door"
  media_dirs:
    front_door: "/media/front_door"
  packages: !include_dir_named packages
  customize: !include customize.yaml
  external_url: !secret ha_base_url
  internal_url: !secret ha_base_url

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

sun:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  server_port: !secret ha_port
  ip_ban_enabled: true
  login_attempts_threshold: 5

python_script:

wake_on_lan:

browser_mod:
  prefix: "browser_"
  disable:
    - all

recorder:
  include:
    domains:
      - switch
      - light
      - climate
      - cover
      - fan
      - device_tracker
      - lock
    entity_globs:
      - sensor.ups_*
      - binary_sensor.*door*
      - binary_sensor.*window*
      - binary_sensor.*motion*
      - binary_sensor.*presence*
      - sensor.power*
    entities:
      - input_select.laundry_machine_status
      - binary_sensor.fridge
      - binary_sensor.freezer
      - binary_sensor.big_freezer
      - sensor.shelly_3em_channel_a_power
      - sensor.shelly_3em_channel_b_power
      - sensor.shelly_3em_channel_c_power
      - sensor.outside_climate_temperature
      - sensor.outside_climate_humidity




lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-mobile:
      mode: yaml
      title: Mobile
      icon: mdi:cellphone
      show_in_sidebar: true
      filename: lovelace_portrait.yaml

    lovelace-tablet:
      mode: yaml
      title: Tablet
      icon: mdi:monitor
      show_in_sidebar: true
      filename: lovelace_landscape.yaml

      
      # resources:
      #   - url: /hacsfiles/button-card/button-card.js
      #     type: module

      #   - url: /hacsfiles/mini-climate-card/mini-climate-card-bundle.js?hacstag=2681639751210
      #     type: module

      #   - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      #     type: module

      #   - url: /hacsfiles/lovelace-fan-xiaomi/fan-xiaomi.js
      #     type: module

      #   - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?hacstag=1485208381150
      #     type: module

      #   - url: /hacsfiles/spotify-card/spotify-card.js?hacstag=173955605240
      #     type: module

      #   - url: /hacsfiles/lovelace-auto-entities/auto-entities.js?hacstag=167744584191
      #     type: module

      #   - url: /webrtc/webrtc-camera.js?v2.2.0
      #     type: module

      #   - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=1512800620110
      #     type: module

      #   - url: /hacsfiles/gallery-card/gallery-card.js?hacstag=284283867331
      #     type: module

      #   - url: /hacsfiles/Home-Assistant-Lovelace-Local-Conditional-card/local-conditional-card.js?hacstag=218178802111
      #     type: module

      #   - url: /hacsfiles/decluttering-card/decluttering-card.js?hacstag=188686483063
      #     type: module

      #   - url: /hacsfiles/lovelace-state-switch/state-switch.js?hacstag=158756598191
      #     type: module

      #   - url: /hacsfiles/scheduler-card/scheduler-card.js?hacstag=286270157233
      #     type: module

      #   - url: /hacsfiles/LG-WebOS-Remote-Control/lg-remote-control.js?hacstag=25700599020738
      #     type: module

      #   - url: /hacsfiles/lovelace-webos-keyboard-card/webos-keyboard-card.js?hacstag=3709970196489
      #     type: module



# logger:
#   default: warning
#   logs:
#     custom_components.webrtc: debug
#     homeassistant.components.heos: debug
#     homeassistant.components.denonavr: debug
#     homeassistant.components.python_script: debug
#     homeassistant.components.python_scripts: debug
#     pydeconz: debug
#     homeassistant.components.deconz: debug
#     custom_components.ekon-local: debug
#     homeassistant.components.shell_command: debug


# lovelace:
#   mode: storage
#   dashboards:
#     lovelace-yaml:
#       mode: yaml
#       filename: lovelace.yaml
#       title: "Home"
#       icon: mdi:view-dashboard
#       show_in_sidebar: true
#       require_admin: true