title: Home

wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  idle_time: 0

decluttering_templates: !include_dir_merge_named /config/lovelace/decluttering_templates/

# button_card_templates: !include_dir_merge_named /config/lovelace/button_card_templates/
button_card_templates: !include_dir_merge_named "custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

views:
  - !include /config/lovelace/views/01_dashboard_landscape.yaml
  - !include /config/lovelace/views/02_front_door.yaml
  - !include /config/lovelace/views/03_ac.yaml
  # - !include /config/lovelace/views/04_power.yaml
  - !include /config/lovelace/views/05_googlespeakers.yaml
  - !include /config/lovelace/views/06_sensors.yaml
  - !include /config/lovelace/views/07_config.yaml
  - !include /config/lovelace/views/08_config_ac.yaml
  - !include /config/lovelace/views/09_servers.yaml
  - !include /config/lovelace/views/10_dev.yaml
  - !include /config/lovelace/views/11_hallway.yaml
  - !include /config/lovelace/views/schedule.yaml
  - !include /config/lovelace/views/12_living_room.yaml
  - !include /config/lovelace/views/13_balcony.yaml
  - !include /config/lovelace/views/14_stealth_mode.yaml
  - !include /config/lovelace/views/15_toilet.yaml
  - !include /config/lovelace/views/16_bathroom.yaml
  - !include /config/lovelace/views/17_office.yaml
  - !include /config/lovelace/views/18_guests.yaml
  - !include /config/lovelace/views/19_riley.yaml
  - !include /config/lovelace/views/20_bedroom.yaml
  - !include /config/lovelace/views/rooms.yaml
