telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_shlomi
      - !secret telegram_inbal

notify:
  - name: shlomi
    platform: telegram
    chat_id: !secret telegram_shlomi
  - name: inbal
    platform: telegram
    chat_id: !secret telegram_inbal

  - name: bffs
    platform: group
    services:
      - service: shlomi
      - service: inbal

script:
  notify_photo:
    mode: parallel
    sequence:
      - service: telegram_bot.send_photo
        data:
          caption: '{{ message }}'
          file: '{{ file }}'
          target: '{{ target }}'

  notify_bffs_photo:
    mode: parallel
    sequence:
      - service: telegram_bot.send_photo
        data:
          caption: '{{ message }}'
          file: '{{ file }}'
          target: !secret telegram_all_chats

  notify_bffs_with_actions:
    mode: parallel
    sequence:
      - service: telegram_bot.send_message
        data:
          message: '{{ message }}'
          target: !secret telegram_all_chats
          inline_keyboard: '{{ inline_keyboard }}'

  notify_with_photo_actions:
    sequence:
      - service: telegram_bot.send_message
        data:
          message: '{{ message }}'
          message_tag: 'front_door_photo'
          target: '{{ target }}'
          inline_keyboard: >
            Front Door Photo:/send_photo {{ front_door_photo }},
            Living Room Photo:/send_photo {{ living_room_photo }}

  notify_shlomi_when_away_with_photo_actions:
    sequence:
      - alias: "Check if Shlomi is not home"
        condition: state
        entity_id: person.shlomi
        state: "not_home"
      - service: script.notify_with_photo_actions
        data:
          message: '{{ message }}'
          target: !secret telegram_shlomi
          front_door_photo: '{{ front_door_photo }}'
          living_room_photo: '{{ living_room_photo }}'

  notify_inbal_when_away_with_photo_actions:
    sequence:
      - alias: "Check if Inbal is not home"
        condition: state
        entity_id: person.inbal
        state: "not_home"
      - service: script.notify_with_photo_actions
        data:
          message: '{{ message }}'
          target: !secret telegram_inbal
          front_door_photo: '{{ front_door_photo }}'
          living_room_photo: '{{ living_room_photo }}'

automation:
  - alias: Telegram callback turn on off
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          command: "/turn_on"
      - platform: event
        event_type: telegram_callback
        event_data:
          command: "/turn_off"
    action:
      - service: python_script.telegram_callback
        data:
          callback_data: '{{ trigger.event.data.data }}'
          callback_query_id: '{{ trigger.event.data.id }}'

  - alias: Telegram callback send photo
    id: Telegram callback send photo
    mode: parallel
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          command: "/send_photo"
    action:
      - service: python_script.telegram_send_photo_callback
        data:
          callback_data: '{{ trigger.event.data.data }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'

