cover:
  - platform: cover_rf_time_based
    devices:
      bedroom_curtain_with_moving_state:
        name: Bedroom Curtain with Moving State
        travelling_time_up: 13.5
        travelling_time_down: 13.5
        cover_entity_id: cover.bedroom_curtain
        send_stop_at_ends: false

sensor:
  - platform: template
    sensors:
      bedroom_curtain_state:
        value_template: >
          {% if states('cover.bedroom_curtain_switch') == 'open' and state_attr("cover.bedroom_curtain_switch", "current_position") == 100 %}
          close
          {% elif states('cover.bedroom_curtain_switch') == 'closed' and state_attr("cover.bedroom_curtain_switch", "current_position") == 0 %}
          open
          {% else %}
          stop
          {% endif %}

automation:
  - alias: Bedroom Curtain According To Sensor
    trigger:
      - platform: state
        entity_id: sensor.bedroom_curtain_state
    action:
      service: "cover.{{trigger.to_state.state}}_cover"
      entity_id:
        - cover.bedroom_curtain

