cover:
  - platform: cover_rf_time_based
    devices:
      birds_shutter:
        name: Birds Shutter
        travelling_time_up: 19
        travelling_time_down: 18
        cover_entity_id: cover.birds_shutter_switch
        send_stop_at_ends: False

sensor:
  - platform: template
    sensors:
      birds_shutter_state:
        value_template: >
          {% if states('cover.birds_shutter_switch') == 'open' and state_attr("cover.birds_shutter_switch", "current_position") == 100 %}
          close
          {% elif states('cover.birds_shutter_switch') == 'closed' and state_attr("cover.birds_shutter_switch", "current_position") == 0 %}
          open
          {% else %}
          stop
          {% endif %}

automation:
  - alias: Birds Shutter Update Position From Physical Switch
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: sensor.birds_shutter_state
        not_from:
          - unknown
          - unavailable
        not_to:
          - unknown
          - unavailable
    condition:
      - alias: "not already in the same state" #Otherwise causes some weird racing condition between template cover and switch
        condition: template
        value_template: "{{ (trigger.to_state.state | replace('open', 'opening') | replace('close', 'closing')) != states('cover.birds_shutter') }}"    
    action:
      service: cover_rf_time_based.set_known_action
      entity_id: cover.birds_shutter
      data:
        action: "{{ trigger.to_state.state }}"
