cover:
  - platform: cover_rf_time_based
    devices:
      birds_shutter:
        name: Birds Shutter
        travelling_time_up: 19
        travelling_time_down: 18
        close_script_entity_id: script.birds_shutter_close
        stop_script_entity_id: script.birds_shutter_stop
        open_script_entity_id: script.birds_shutter_open
        send_stop_at_ends: False

sensor:
  - platform: template
    sensors:
      birds_shutter_state:
        value_template: >
          {% if states('cover.birds_shutter_switch') == 'open' and state_attr("cover.birds_shutter_switch", "current_position") == 100 %}
          close
          {% elif states('cover.birds_shutter_switch') == 'open' and state_attr("cover.birds_shutter_switch", "current_position") == 50 %}
          stop
          {% elif states('cover.birds_shutter_switch') == 'closed' and state_attr("cover.birds_shutter_switch", "current_position") == 0 %}
          open
          {% endif %}

automation:
  - alias: Birds Shutter Update Position From Physical Switch
    trigger:
      - platform: state
        entity_id: sensor.birds_shutter_state
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: cover.birds_shutter
            state: 
              - "closing"
              - "opening"
    action:
      service: cover_rf_time_based.set_known_action
      entity_id: cover.birds_shutter
      data:
        action: "{{ trigger.to_state.state }}"

script:
  birds_shutter_open:
    sequence:
      service: cover.open_cover
      entity_id: cover.birds_shutter_switch
  birds_shutter_close:
    sequence:
      service: cover.close_cover
      entity_id: cover.birds_shutter_switch
  birds_shutter_stop:
    sequence:
      service: cover.stop_cover
      entity_id: cover.birds_shutter_switch
