cover:
  - platform: cover_rf_time_based
    devices:
      kitchen_shutter:
        name: Kitchen Shutter
        travelling_time_up: 15
        travelling_time_down: 15
        cover_entity_id: cover.kitchen_shutter_switch
        send_stop_at_ends: False

sensor:
  - platform: template
    sensors:
      kitchen_shutter_state:
        value_template: >
          {% if states('cover.kitchen_shutter_switch') == 'open' and state_attr("cover.kitchen_shutter_switch", "current_position") == 100 %}
          close
          {% elif states('cover.kitchen_shutter_switch') == 'closed' and state_attr("cover.kitchen_shutter_switch", "current_position") == 0 %}
          open
          {% else %}
          stop
          {% endif %}

automation:
  - alias: Kitchen Shutter Update Position From Physical Switch
    trigger:
      - platform: state
        entity_id: sensor.kitchen_shutter_state
    condition:
      - alias: "not already in the same state" #Otherwise causes some weird racing condition between template cover and switch
        condition: template
        value_template: "{{ (trigger.to_state.state | replace('open', 'opening') | replace('close', 'closing')) != states('cover.kitchen_shutter') }}"
    action:
      service: cover_rf_time_based.set_known_action
      entity_id: cover.kitchen_shutter
      data:
        action: "{{ trigger.to_state.state }}"
