cover:
  - platform: cover_rf_time_based
    devices:
      kitchen_curtain:
        name: Kitchen Curtain
        travelling_time_up: 17.5
        travelling_time_down: 17
        close_script_entity_id: script.kitchen_curtain_close
        stop_script_entity_id: script.kitchen_curtain_stop
        open_script_entity_id: script.kitchen_curtain_open
        send_stop_at_ends: False

sensor:
  - platform: template
    sensors:
      kitchen_curtain_state:
        value_template: >
          {% if states('cover.kitchen_curtain_switch') == 'open' and state_attr("cover.kitchen_curtain_switch", "current_position") == 100 %}
          close
          {% elif states('cover.kitchen_curtain_switch') == 'open' and state_attr("cover.kitchen_curtain_switch", "current_position") == 50 %}
          stop
          {% elif states('cover.kitchen_curtain_switch') == 'closed' and state_attr("cover.kitchen_curtain_switch", "current_position") == 0 %}
          open
          {% endif %}

automation:
  - alias: Kitchen Curtain Update Position From Physical Switch
    trigger:
      - platform: state
        entity_id: sensor.kitchen_curtain_state
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: cover.kitchen_curtain
            state: 
              - "closing"
              - "opening"
    action:
      service: cover_rf_time_based.set_known_action
      entity_id: cover.kitchen_curtain
      data:
        action: "{{ trigger.to_state.state }}"

script:
  kitchen_curtain_open:
    sequence:
      service: cover.open_cover
      entity_id: cover.kitchen_curtain_switch
  kitchen_curtain_close:
    sequence:
      service: cover.close_cover
      entity_id: cover.kitchen_curtain_switch
  kitchen_curtain_stop:
    sequence:
      service: cover.stop_cover
      entity_id: cover.kitchen_curtain_switch
