cover:
  - platform: cover_rf_time_based
    devices:
      living_room_shutter:
        name: Living Room Shutter
        travelling_time_up: 28
        travelling_time_down: 26.5
        cover_entity_id: cover.living_room_shutter_switch
        send_stop_at_ends: False

sensor:
  - platform: template
    sensors:
      living_room_shutter_state:
        value_template: >
          {% if states('cover.living_room_shutter_switch') == 'open' and state_attr("cover.living_room_shutter_switch", "current_position") == 100 %}
          close
          {% elif states('cover.living_room_shutter_switch') == 'closed' and state_attr("cover.living_room_shutter_switch", "current_position") == 0 %}
          open
          {% else %}
          stop
          {% endif %}

automation:
  - alias: Living Room Shutter Update Position From Physical Switch
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: sensor.living_room_shutter_state
        not_from:
          - unknown
          - unavailable
        not_to:
          - unknown
          - unavailable
    condition:
      - alias: "not already in the same state" #Otherwise causes some weird racing condition between template cover and switch
        condition: template
        value_template: "{{ (trigger.to_state.state | replace('open', 'opening') | replace('close', 'closing')) != states('cover.living_room_shutter') }}"    
    action:
      service: cover_rf_time_based.set_known_action
      entity_id: cover.living_room_shutter
      data:
        action: "{{ trigger.to_state.state }}"
