sensor:
  - platform: template
    sensors:
      living_room_curtain_state:
        value_template: >
          {% if states('cover.living_room_curtain_switch') == 'open' and state_attr("cover.living_room_curtain_switch", "current_position") == 100 %}
          close
          {% elif states('cover.living_room_curtain_switch') == 'closed' and state_attr("cover.living_room_curtain_switch", "current_position") == 0 %}
          open
          {% else %}
          stop
          {% endif %}

automation:
  - alias: Living Room Curtain According To Sensor
    trigger:
      - platform: state
        entity_id: sensor.living_room_curtain_state
    action:
      service: "cover.{{trigger.to_state.state}}_cover"
      entity_id:
        - cover.living_room_curtain

