cover:
  - platform: cover_rf_time_based
    devices:
      office_shutter:
        name: Office Shutter
        travelling_time_up: 19
        travelling_time_down: 19
        close_script_entity_id: script.office_shutter_close
        stop_script_entity_id: script.office_shutter_stop
        open_script_entity_id: script.office_shutter_open
        send_stop_at_ends: False

sensor:
  - platform: template
    sensors:
      office_shutter_state:
        value_template: >
          {% if states('cover.office_shutter_switch') == 'open' and state_attr("cover.office_shutter_switch", "current_position") == 100 %}
          close
          {% elif states('cover.office_shutter_switch') == 'open' and state_attr("cover.office_shutter_switch", "current_position") == 50 %}
          stop
          {% elif states('cover.office_shutter_switch') == 'closed' and state_attr("cover.office_shutter_switch", "current_position") == 0 %}
          open
          {% endif %}

automation:
  - alias: Office Shutter Update Position From Physical Switch
    trigger:
      - platform: state
        entity_id: sensor.office_shutter_state
    condition:
      - alias: "not already in the same state" #Otherwise causes some weird racing condition between template cover and switch
        condition: template
        value_template: "{{ (trigger.to_state.state | replace('open', 'opening') | replace('close', 'closing')) != states('cover.office_shutter') }}"    
    action:
      service: cover_rf_time_based.set_known_action
      entity_id: cover.office_shutter
      data:
        action: "{{ trigger.to_state.state }}"

script:
  office_shutter_open:
    sequence:
      service: cover.open_cover
      entity_id: cover.office_shutter_switch
  office_shutter_close:
    sequence:
      service: cover.close_cover
      entity_id: cover.office_shutter_switch
  office_shutter_stop:
    sequence:
      service: cover.stop_cover
      entity_id: cover.office_shutter_switch
