automation:
  - alias: Bathroom light on motion
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bathroom_door
        from: 'off'
        to: 'on'
    action:
      - choose:
        - conditions:
          - condition: time
            after: input_datetime.morning
            before: input_datetime.night
          sequence:
            - service: light.turn_on
              entity_id: light.bathroom_main
        - conditions:
          - condition: time
            after: input_datetime.night
            before: input_datetime.late_night
          sequence:
            - service: light.turn_on
              entity_id: light.bathroom_laundry
        - conditions:
          - condition: time
            after: input_datetime.late_night
            before: input_datetime.morning
          sequence:
            - service: light.turn_on
              entity_id: light.bathroom_cabinet_controller
      - delay:
          seconds: 5
          
  - alias: Bathroom light off when no motion
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        from: 'on'
        to: 'off'
        for:
          minutes: 25
    action:
      - service: light.turn_off
        entity_id: 
          - light.bathroom_main
          - light.bathroom_cabinet_controller

switch:
  - platform: broadlink
    mac: !secret office_mac
    switches:
      - name: Bathroom Cabinet Smart Plug
        command_on: 'shQyABEFEQUHEAcQEQUHEBEGEQYHEBEGBxAHEBEGEQYRBgcQBhAGEBEGBhARBREFBhARBQaiAAAAAAAA'
        command_off: 'shIyABEFEQUGEAYQBhARBQYQBxARBQYQEQYGohEFEQUGEAYQEQUHEBEFEQUHEBEFBxAGEBEFAAAAAAAA'

group:
  shower:
    entities:
      - switch.water_boiler
      - switch.bathroom_heater

script:
  toggle_shower:
    variables:
      action: switch.turn_{{ 'on' if states('group.shower') == 'off' else 'off' }}
    sequence:
      - service: "{{ action }}"
        entity_id: switch.water_boiler
      - delay:
          seconds: 2
      - service: "{{ action }}"
        entity_id: switch.bathroom_heater