group:
  closet_light_automations:
    entities:
      - automation.bedroom_closet_light_on_motion
      - automation.bedroom_closet_light_off_when_no_motion

automation:
  - alias: Bedroom closet light on motion

    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_closet_motion
        from: 'off'
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.bedroom_closet
          
  - alias: Bedroom closet light off when no motion
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_closet_motion
        from: 'on'
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.bedroom_closet