automation:
  - alias: Inbal came home
    trigger:
      - platform: state
        entity_id: person.inbal
        from: not_home
        to: home

    action:
      - service: notify.bffs
        data:
          message: 'Bffushkit is {{trigger.to_state.state}}'

      - service: script.navigate_to_entrace_card
        data:
          browser_id: "{{ trigger.to_state.entity_id | replace('person.', '') }}_app"

  - alias: Shlomi came home
    trigger:
      - platform: state
        entity_id: person.shlomi
        from: not_home
        to: home
    action:
      - service: notify.shlomi
        data:
          message: 'Bffush is {{ trigger.to_state.state }}'

      - service: script.navigate_to_entrace_card
        data:
          browser_id: "{{ trigger.to_state.entity_id | replace('person.', '') }}_app"

script:
  navigate_to_entrace_card:
    mode: parallel
    sequence:
      - alias: "Wait until the Home Assistant app connection is available"
        wait_template: "{{ is_state('sensor.' + browser_id + '_browser_visibility', 'visible') }}"
        timeout:
          seconds: 20
        continue_on_timeout: false

      - service: browser_mod.popup
        data:
          title: Welcome Home
          content: !include /config/lovelace/cards/quick_status_entrance.yaml
          browser_id:
            - "{{ browser_id }}"
