input_boolean:
  guest_mode:

automation:
  - id: Guest Mode - turn off when returning home
    alias: Guest Mode - turn off when returning home
    trigger:
      - platform: state
        entity_id: group.bffs
        from: "not_home"
        to: "home"
    condition:
      - alias: "Guest Mode has been on for more than 30 minutes"
        condition: state
        entity_id: input_boolean.guest_mode
        state: "on"
        for:
          minutes: 30
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode
      - service: notify.bffs
        data:
          message: "Welcome back home! Guest Mode has been turned off."

  - id: Guest Mode - Select Hebrew for House Tablet
    alias: Guest Mode - Select Hebrew for House Tablet
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        from: 'off'
        to: 'on'

    condition:
      - condition: not
        conditions:    
          - alias: "House Tablet is (not) in Hebrew mode"
            condition: state
            entity_id: input_select.local_lang_house_tablet
            state: "hebrew"
        
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.local_lang_house_tablet
          option: hebrew


switch:
  - platform: template
    switches:
      guest_schedules:
        friendly_name: "Guest Schedules"
        value_template: "{{ (states.switch | selectattr('entity_id', 'search', 'switch.schedule_guests_*') | selectattr('state', 'eq', 'on') | list | length) != 0 }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: "{{ states.switch | selectattr('entity_id', 'search', 'switch.schedule_guests_*') | map(attribute='entity_id') | list }}"

        turn_off:
          service: switch.turn_off
          target:
            entity_id: "{{ states.switch | selectattr('entity_id', 'search', 'switch.schedule_guests_*') | map(attribute='entity_id') | list }}"
