automation:
  - alias: House humidity high
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.living_room_climate_humidity
          - sensor.office_climate_humidity
          - sensor.guests_climate_humidity
          - sensor.riley_climate_humidity
          - sensor.bedroom_climate_humidity
          - sensor.bedroom_closet_climate_humidity
        above: 70
      - platform: numeric_state
        entity_id: sensor.bedroom_closet_humidity
        above: 67
    action:
      - service: notify.bffs
        data:
          message: >
            {{ trigger.to_state.attributes.friendly_name }} humidity is {{ trigger.to_state.state }}%.
            {% if ((states('sensor.outside_climate_humidity') | int) - 5) <= (states('sensor.office_humidity') | int) %}Time to open the windows.{% else %}Time to turn on the AC.{% endif %}

  - alias: House temp is extreme - notify on telegram
    trigger:
      - platform: state
        entity_id:
          - sensor.living_room_temperature_monitor
          - sensor.office_temperature_monitor
          - sensor.guests_temperature_monitor
          - sensor.riley_temperature_monitor
          - sensor.bedroom_temperature_monitor
        to:
          - "Very Hot"
          - "Very Cold"
    action:
      - service: script.turn_on
        target:
          entity_id: script.telegram_message_with_ac_buttons
        data:
          variables:
            message: "{{ trigger.to_state.attributes.friendly_name }} temperature is {{ trigger.to_state.state | lower }} ({{ states(trigger.to_state.entity_id | replace('_monitor', ''))}})."
            room_friendly_name: "{{ trigger.to_state.attributes.friendly_name | replace(' Temperature', '') }}"

script:
  telegram_message_with_ac_buttons:
    sequence:
      - service: script.notify_bffs_with_actions
        data:
          message: "{{ message }}"
          inline_keyboard: >
            {{ room_friendly_name }} AC On:/turn_on climate.ac_damper_{{ room_friendly_name | string | regex_replace(find=' ', replace='_', ignorecase=True)| lower }},
            {{ room_friendly_name }} AC Off:/turn_off climate.ac_damper_{{ room_friendly_name | string | regex_replace(find=' ', replace='_', ignorecase=True)| lower }}
