automation:
  - alias: House humidity high
    trigger:
      - platform: numeric_state
        entity_id: 
          - sensor.living_room_humidity
          - sensor.office_humidity
          - sensor.birds_humidity
          - sensor.riley_humidity
          - sensor.bedroom_humidity
          - sensor.bedroom_closet_humidity
        above: 70
      - platform: numeric_state
        entity_id: sensor.bedroom_closet_humidity
        above: 67
    action:
      - service: notify.bffs
        data:
          message: "{{ trigger.to_state.attributes.friendly_name }} humidity is {{ trigger.to_state.state }}%. Time to open the windows."

  - alias: House temp too low
    trigger:
      - platform: numeric_state
        entity_id: 
          - sensor.living_room_temperature
          - sensor.office_temperature
          - sensor.birds_temperature
          - sensor.riley_temperature
          - sensor.bedroom_temperature
        below: 19
    action:
      - service: script.telegram_message_with_ac_buttons
        data:
          message: "{{ trigger.to_state.attributes.friendly_name }} temperature is too cold ({{ trigger.to_state.state }}). Heating needed."
          room_friendly_name: '{{ trigger.to_state.attributes.friendly_name }}'

  - alias: House temp too high
    trigger:
      - platform: numeric_state
        entity_id: 
          - sensor.living_room_temperature
          - sensor.office_temperature
          - sensor.birds_temperature
          - sensor.riley_temperature
          - sensor.bedroom_temperature
        above: 29
    action:
      - service: script.telegram_message_with_ac_buttons
        data:
          message: "{{ trigger.to_state.attributes.friendly_name }} temperature is too hot ({{ trigger.to_state.state }}). Cooling needed."
          room_friendly_name: '{{ trigger.to_state.attributes.friendly_name }}'

script:
  telegram_message_with_ac_buttons:
    sequence:
      - service: script.notify_bffs_with_actions
        data:
          message: "{{ message }}"
          inline_keyboard: >
            {{ room_friendly_name }} AC On:/turn_on:fan.ac_damper_{{ room_friendly_name | string | regex_replace(find=' ', replace='_', ignorecase=True)| lower }},
            {{ room_friendly_name }} AC Off:/turn_off:fan.ac_damper_{{ room_friendly_name | string | regex_replace(find=' ', replace='_', ignorecase=True)| lower }}
