automation:
- alias: Intercom Turn off after 1 second
  mode: parallel
  trigger:
      - platform: state
        entity_id:
          - switch.intercom
        from: 'off'
        to: 'on'
        for:
          seconds: 1
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.intercom
