binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: "Google Connection"
    scan_interval: 60

  - platform: template
    sensors:
      internet_connection:
        friendly_name: Internet Connection
        value_template: "{{ states('binary_sensor.google_connection') == 'on' and states('binary_sensor.ubnt_interface_eth10_connected') == 'on'}}"
        device_class: connectivity
