input_boolean:
  riley_is_sleeping:

script:
  update_riley_sleeping_status:
    sequence:
      - service: input_boolean.turn_{{ status }}
        entity_id: input_boolean.riley_is_sleeping

input_datetime:
  riley_goes_to_sleep:
    name: Riley Goes to Sleep
    has_date: false
    has_time: true

automation:
  - id: Riley is Sleeping - Start
    alias: Riley is Sleeping - Start
    trigger:
      - platform: state
        entity_id: 
          - switch.house_tablet_screen
          - switch.black_tablet_screen
        from: "off"
        to: "on"
      - platform: state
        entity_id: sensor.house_tablet_foreground_app
        to: "com.mcu.reolink"
    condition:
      - alias: "At night time"
        condition: time
        after: input_datetime.riley_goes_to_sleep
        before: input_datetime.dawn
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.riley_is_sleeping

  - id: Riley is Sleeping - End
    alias: Riley is Sleeping - End
    trigger:
      - platform: time
        at: input_datetime.dawn
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.riley_is_sleeping

  - id: Riley Light - Turn off when no movement
    alias: Riley Light - Turn off when no movement
    trigger:
      - platform: state
        entity_id: binary_sensor.riley_motion
        from: "on"
        to: "off"
        for:
          minutes: 30
    condition:
      - and:
        - alias: "Riley light is on"
          condition: state
          entity_id: light.riley_main
          state: "on"
        - alias: "Riley is awake"
          condition: state
          entity_id: input_boolean.riley_is_sleeping
          state: "off"
    action:
      - service: light.turn_off
        target:
          entity_id: light.riley_main