group:
  scenes:
    entities:
      - switch.evening_scene
      - switch.sleep_scene
      - switch.housekeeper_unlock_and_lock_door
      - switch.dance_freeze_game

mqtt:
  scene:
    - name: Z2M Evening Living Room Area
      unique_id: z2m_evening_living_room_area
      command_topic: "zigbee2mqtt/master_living_room/set"
      payload_on: '{"scene_recall": 0}'

    - name: Z2M Evening Bedroom Area
      unique_id: z2m_evening_bedroom_area
      command_topic: "zigbee2mqtt-bedroom/master_bedroom/set"
      payload_on: '{"scene_recall": 0}'

scene:
  - name: Sleep
    icon: "mdi:sleep"
    entities:
      light.all_lights: off
      # cover.bedroom_shutter:
      #   state: open
      #   current_position: 11
      lock.front_door: "locked"
      switch.house_tablet_screen: off
      media_player.living_room_tv: off

sensor:
  - platform: template
    sensors:
      sleep_scene:
        friendly_name: "Sleep Scene"
        value_template: "{{ (is_state('group.all_lights', 'off') and
          is_state('lock.front_door', 'locked') and
          is_state('switch.house_tablet_screen', 'off') and
          is_state('media_player.living_room_tv', 'off')) | replace(true, 'on') | replace(false, 'off') }}"
          # is_state_attr('cover.bedroom_shutter', 'current_position', 11) and

switch:
  - platform: template
    switches:
      evening_scene:
        value_template: "{{ (is_state('light.living_room_side_lamp', 'on') and
          is_state('light.kitchen_island', 'on') and

          is_state('light.living_room_entrance', 'off') and
          is_state('light.living_room_hallway', 'off') and
          is_state('light.living_room_fan', 'off') and
          is_state('light.living_room_tv_light', 'off') and
          is_state('light.living_room_curtain_light', 'off') and

          is_state('light.kitchen_counter', 'off') and
          is_state('light.kitchen_pantry', 'off') and

          is_state('light.balcony_lights', 'off') and
          is_state('light.toilet_lights', 'off') and
          is_state('light.bathroom_lights', 'off') and
          is_state('light.hallway_lights', 'off') and
          is_state('light.office_lights', 'off') and
          is_state('light.guests_main', 'off') and
          is_state('light.riley_main', 'off') and
          is_state('light.bedroom_lights', 'off')) | replace(true, 'on') | replace(false, 'off') }}"
        turn_on:
          service: scene.turn_on
          target:
            entity_id:
              - scene.z2m_evening_bedroom_area
              - scene.z2m_evening_living_room_area

        turn_off:
          service: light.turn_off
          target:
            entity_id:
              - light.all_lights


      sleep_scene:
        value_template: "{{ (is_state('group.all_lights', 'off') and
          is_state('lock.front_door', 'locked') and
          is_state('switch.house_tablet_screen', 'off') and
          is_state('media_player.living_room_tv', 'off')) | replace(true, 'on') | replace(false, 'off') }}"
        turn_on:
          - service: lock.lock
            target:
              entity_id: lock.front_door

          - service: homeassistant.turn_off
            target:
              entity_id:
                - light.all_lights
                - switch.house_tablet_screen
                - media_player.living_room_tv

        turn_off:
          service: light.turn_on
          target:
            entity_id:
              - light.living_room_lights
