automation:
  - alias: Stairs light auto on
    mode: single
    trigger: #Turn on when either door is opened or there is motion
      - platform: state
        entity_id: 
          - binary_sensor.front_door
          - binary_sensor.stairs_motion
        from: "off"
        to: "on"
    action:
      - service: light.turn_on
        entity_id: light.stairs_group

  - alias: Stairs light auto off
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.front_door
          - binary_sensor.stairs_motion
        from: "on"
        to: "off"
    condition: #Turn off only if both door is closed and there is no motion
      condition: state
      entity_id: 
        - binary_sensor.front_door
        - binary_sensor.stairs_motion
      state: 
        - 'off'
        - 'unavailable'
    action:
      - service: light.turn_off
        entity_id: light.stairs_group

  - alias: Stairs light off when front door is open for 5 mins
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        from: "off"
        to: "on"
        for:
          minutes: 5
    condition:
      condition: state
      entity_id: binary_sensor.stairs_motion
      state: 
        - 'off'
        - 'unavailable'
    action:
      - service: light.turn_off
        entity_id: light.stairs_group