sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "time_date"
      - "time_utc"

input_datetime:
  dawn:
    name: Dawn
    has_date: false
    has_time: true
  morning:
    name: Morning
    has_date: false
    has_time: true
  late_morning:
    name: Late Morning
    has_date: false
    has_time: true
  noon:
    name: Noon
    has_date: false
    has_time: true
  evening:
    name: Evening
    has_date: false
    has_time: true
  evening_2:
    name: Evening 2
    has_date: false
    has_time: true
  night:
    name: Night
    has_date: false
    has_time: true
  late_night:
    name: Late Night
    has_date: false
    has_time: true

automation:
  - alias: Guests Turn On Lights Late Morning
    trigger:
      platform: time
      at: input_datetime.late_morning
    action:
      - service: light.turn_on
        entity_id: light.guests_main_combined

  - alias: Guests Dim Lights Evening
    trigger:
      platform: time
      at: input_datetime.evening
    action:
      - service: light.turn_on
        entity_id: light.guests_main_combined
      - delay:
          seconds: 20
      - service: light.turn_on
        entity_id: light.guests_main_combined
        data:
          brightness: 1

  - alias: Guests Turn Off Lights Evening 2
    trigger:
      platform: time
      at: input_datetime.evening_2
    action:
      - service: light.turn_off
        entity_id: light.guests_main_combined

  - alias: Open Shutter Noon - guests & office
    trigger:
      platform: time
      at: input_datetime.noon
    action:
      - service: cover.set_cover_position
        data:
          entity_id:
            - cover.guests_shutter
            - cover.office_shutter
          position: 100

  - alias: Guests turn off light noon
    trigger:
      platform: time
      at: input_datetime.noon
    action:
      - delay:
          seconds: 30
      - service: light.turn_off
        entity_id: light.guests_main_combined

  - alias: Guests Close Shutter Night
    trigger:
      platform: time
      at: input_datetime.night
    action:
      - service: cover.close_cover
        entity_id: cover.guests_shutter

  - alias: Guests Open Shutter Partly Morning
    trigger:
      platform: time
      at: input_datetime.morning
    action:
      - service: cover.set_cover_position
        data:
          entity_id: cover.guests_shutter
          position: 40

  - alias: Living Room Lamp Turn Brightness Down at Night
    trigger:
      - platform: state
        entity_id: light.living_room_lamp_hue
        from: "unavailable"
        to: "on"
    condition:
      - condition: time
        after: input_datetime.night
        before: input_datetime.late_morning
    action:
      - service: light.turn_on
        entity_id: light.living_room_lamp_hue
        data:
          brightness: 2

  - alias: Bathroom Laundry Turn Brightness Down at Night
    trigger:
      - platform: state
        entity_id: light.laundry_hue
        from: "unavailable"
        to: "on"
    condition:
      - condition: time
        after: input_datetime.night
        before: input_datetime.late_morning
    action:
      - service: light.turn_on
        entity_id: light.laundry_hue
        data:
          brightness: 2

  - alias: Office Close Shutter Partly Late Night
    trigger:
      platform: time
      at: input_datetime.late_night
    action:
      - service: cover.set_cover_position
        data:
          entity_id: cover.office_shutter
          position: 35
