sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "time_date"
      - "time_utc"

input_datetime:
  dawn:
    name: Dawn
    has_date: false
    has_time: true
  morning:
    name: Morning
    has_date: false
    has_time: true
  late_morning:
    name: Late Morning
    has_date: false
    has_time: true
  noon:
    name: Noon
    has_date: false
    has_time: true
  evening:
    name: Evening
    has_date: false
    has_time: true
  evening_2:
    name: Evening 2
    has_date: false
    has_time: true
  night:
    name: Night
    has_date: false
    has_time: true
  late_night:
    name: Late Night
    has_date: false
    has_time: true
