group:
  toilet_light_automations:
    entities:
      - automation.toilet_light_on_motion

  toilet_vent_automations:
    entities:
      - automation.toilet_turn_on_vent_if_theres_someone_in_the_toilet_for_a_few_mins
      - automation.toilet_turn_off_vent_automatically


binary_sensor:
  - platform: group
    name: "Toilet Occupancy"
    unique_id: "Toilet Occupancy"
    device_class: occupancy
    entities:
      - binary_sensor.toilet_motion
      - binary_sensor.toilet_presence

automation:

  - alias: Toilet light on motion
    mode: single
    trigger:

      - id: 'on'
        platform: state
        entity_id: 
          - binary_sensor.toilet_occupancy
          - binary_sensor.toilet_door
        from: 'off'
        to: 'on'

      - id: 'off'
        platform: state
        entity_id: binary_sensor.toilet_occupancy
        from: 'on'
        to: 'off'

    action:
      - service: light.turn_{{ trigger.id }}
        entity_id: light.toilet_lights

  - alias: Toilet turn on vent if theres someone in the toilet for a few mins
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_occupancy
        from: 'off'
        to: 'on'
        for:
          minutes: 5
    action:
      #Wait for them to leave the toilet
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.toilet_occupancy
            from: "on"
            to: "off"

      #Make it smell better
      - service: switch.turn_on
        entity_id: switch.toilet_vent

  - alias: Toilet turn off vent automatically
    mode: restart
    trigger:
      - platform: state
        entity_id: switch.toilet_vent
        to: 'on'
        for:
          minutes: 8

    action:
      - service: switch.turn_off
        entity_id: switch.toilet_vent

switch:

  - platform: broadlink
    mac: !secret office_mac
    switches:
      - name: Toilet Night Light
        command_on: 'siAyAAcQEQUGEBEFEQUGEBEFBxAGEBEFEQURBQYQBxAHEBEFBhARBQcPBw8RBQaiEQURBQYQAAAAAAAA'
        command_off: 'siQyABEFEQUGEAcQEQUGEBEFEQUGEBEFBxAGEBEFEQURBQYQBxAGDxEFBhAGEAYQBxARBQeiAAAAAAAA'
