group:
  toilet_light_automations:
    entities:
      - automation.toilet_light_on_motion
      - automation.toilet_turn_on_vent_if_theres_someone_in_the_toilet_for_a_few_mins

automation:

  - alias: Toilet light on motion
    mode: single
    trigger:

      - id: 'on'
        platform: state
        entity_id: 
          - binary_sensor.toilet_motion
          - binary_sensor.toilet_presence
          - binary_sensor.toilet_door
        from: 'off'
        to: 'on'

      - id: 'off'
        platform: state
        entity_id: binary_sensor.toilet_presence
        from: 'on'
        to: 'off'

    action:
      - service: light.turn_{{ trigger.id }}
        entity_id: light.toilet_lights

  - alias: Toilet Turn on vent if theres someone in the toilet for a few mins
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_presence
        from: 'off'
        to: 'on'
        for:
          minutes: 5
    action:
      #Wait for them to leave the toilet
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.toilet_presence
            from: "on"
            to: "off"

      #Make it smell better
      - service: switch.turn_on
        entity_id: switch.toilet_vent
      - delay:
          minutes: 8
      - service: switch.turn_off
        entity_id: switch.toilet_vent

switch:
  # - platform: broadlink
  #   mac: !secret office_mac
  #   switches:
  #     - name: Toilet Vent
  #       command_on: 'si4yABEFEQUHDwcPEQUHDxEFEQUHDxEFBxAHDxEFEQURBQcQBw8HDxEFBw8RBQcQEQURBQehAAAAAAAA'
  #       command_off: 'sm0yABEFEQURBQcPBw8HDxEFBw8HDwcPEgURBQehEgUSBQcPBw8RBQcPEQURBQcPEQUHDwcPAAAAAAAA'

  - platform: broadlink
    mac: !secret office_mac
    switches:
      - name: Toilet Night Light
        command_on: 'siAyAAcQEQUGEBEFEQUGEBEFBxAGEBEFEQURBQYQBxAHEBEFBhARBQcPBw8RBQaiEQURBQYQAAAAAAAA'
        command_off: 'siQyABEFEQUGEAcQEQUGEBEFEQUGEBEFBxAGEBEFEQURBQYQBxAGDxEFBhAGEAYQBxARBQeiAAAAAAAA'
