automation:
  - alias: Toilet light on motion
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_motion
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.toilet_door
        from: 'off'
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.toilet_main
      - delay:
          seconds: 5
          
  - alias: Toilet light off when no motion when door closed
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_motion
        from: 'on'
        to: 'off'
        for:
          minutes: 20
    condition:   
      - condition: state
        entity_id: binary_sensor.toilet_door
        state:  'off'
    action:
      - service: light.turn_off
        entity_id: light.toilet_main

  - alias: Toilet light off when no motion when door is open
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_motion
        from: 'on'
        to: 'off'
    condition:   
      - condition: state
        entity_id: binary_sensor.toilet_door
        state:  'on'
    action:
      - service: light.turn_off
        entity_id: light.toilet_main

  - alias: Toilet Turn on vent after flushing
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.toilet_flush
        from: 'off'
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.toilet_vent
      - delay:
          minutes: 5
      - service: switch.turn_off
        entity_id: switch.toilet_vent

switch:
  - platform: broadlink
    mac: !secret office_mac
    switches:
      - name: Toilet Vent
        command_on: 'si4yABEFEQUHDwcPEQUHDxEFEQUHDxEFBxAHDxEFEQURBQcQBw8HDxEFBw8RBQcQEQURBQehAAAAAAAA'
        command_off: 'sm0yABEFEQURBQcPBw8HDxEFBw8HDwcPEgURBQehEgUSBQcPBw8RBQcPEQURBQcPEQUHDwcPAAAAAAAA'