## Button 1: Sleep
## Button 2: Bedroom Curtain
## Button 3: Bedroom Shutter
## Button 4: Black Tablet


automation:
  - id: Bedroom Hue Remote Actions
    alias: Bedroom Hue Remote Actions
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          device_id: !secret bedroom_hue_remote_device_id
    variables:
      button_code: "{{ trigger.event.data.event }}"
    action:
      - alias: "choose button"
        choose:
          ## Button 1 Release Hold: Sleep
          - conditions: "{{ button_code == 1003 }}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.sleep

          ## Button 2 Release Short Press When in Motion: Stop Bedroom Curtain
          - conditions: "{{ button_code == 2002 and (is_state('cover.bedroom_curtain_with_moving_state', 'opening') or is_state('cover.bedroom_curtain_with_moving_state', 'closing')) }}"
            sequence:
              - service: cover.stop_cover
                entity_id: cover.bedroom_curtain_with_moving_state

          ## Button 2 Release Short Press: Close Bedroom Curtain
          - conditions: "{{ button_code == 2002 }}"
            sequence:
              - service: cover.close_cover
                entity_id: cover.bedroom_curtain_with_moving_state

          ## Button 2 Hold: Open Bedroom Curtain
          - conditions: "{{ button_code == 2001 }}"
            sequence:
              - service: cover.open_cover
                entity_id: cover.bedroom_curtain_with_moving_state

          ## Button 2 Release Hold: Stop Bedroom Curtain
          # - conditions: "{{ button_code == 2003 }}"
          #   sequence:
          #     - service: cover.stop_cover
          #       entity_id: cover.bedroom_curtain_with_moving_state


          ## Button 2 Release Short Press When in Motion: Stop Bedroom Shutter
          - conditions: "{{ button_code == 3002 and (is_state('cover.bedroom_shutter', 'opening') or is_state('cover.bedroom_shutter', 'closing')) }}"
            sequence:
              - service: cover.stop_cover
                entity_id: cover.bedroom_shutter

          ## Button 2 Release Short Press: Close Bedroom Shutter
          - conditions: "{{ button_code == 3002 }}"
            sequence:
              - service: cover.close_cover
                entity_id: cover.bedroom_shutter

          ## Button 2 Hold: Open Bedroom Shutter
          - conditions: "{{ button_code == 3001 }}"
            sequence:
              - service: cover.open_cover
                entity_id: cover.bedroom_shutter

          ## Button 2 Release Hold: Stop Bedroom Shutter
          # - conditions: "{{ button_code == 3003 }}"
          #   sequence:
          #     - service: cover.stop_cover
          #       entity_id: cover.bedroom_shutter



          ## Button 4 Short Press: Black Tablet
          - conditions: "{{ button_code == 4000 }}"
            sequence:
              - service: switch.toggle
                entity_id: switch.black_tablet
