## Button 1: Sleep
## Button 2: Bedroom Curtain
## Button 3: Bedroom Shutter
## Button 4: Black Tablet


automation:
  - id: Bedroom Hue Remote Actions
    alias: Bedroom Hue Remote Actions
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          device_id: !secret bedroom_hue_remote_device_id
    variables:
      button_code: "{{ trigger.event.data.event }}"
    action:
      - alias: "choose button"
        choose:
          ## Button 1 Long Press: Sleep
          - conditions: "{{ button_code == 1003 }}"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.sleep

          ## Button 2 Short Press/Hold: Start Bedroom Curtain
          - conditions: "{{ button_code == 2000 }}"
            sequence:
              - service: "{{ iif (is_state('cover.bedroom_curtain', 'open'), 'cover.close_cover', 'cover.open_cover') }}"
                entity_id: cover.bedroom_curtain

          ## Button 2 Stop Long Press: Stop Bedroom Curtain
          - conditions: "{{ button_code == 2003 }}"
            sequence:
              - service: cover.stop_cover
                entity_id: cover.bedroom_curtain

          ## Button 3 Short Press/Hold: Bedroom Shutter
          - conditions: "{{ button_code == 3000 }}"
            sequence:
              - service: "{{ iif (is_state('cover.bedroom_shutter', 'open'), 'cover.close_cover', 'cover.open_cover') }}"
                entity_id: cover.bedroom_shutter

          ## Button 3 Stop Long Press: Bedroom Shutter
          - conditions: "{{ button_code == 3003 }}"
            sequence:
              - service: cover.stop_cover
                entity_id: cover.bedroom_shutter

          ## Button 4 Long Press: Black Tablet
          - conditions: "{{ button_code == 4000 }}"
            sequence:
              - service: switch.toggle
                entity_id: switch.black_tablet
