camera:
  - platform: reolink_dev
    name: Front Door
    host: !secret camera_front_door_ip
    username: !secret camera_front_door_username
    password: !secret camera_front_door_password
    stream: sub

  - platform: reolink_dev
    name: Living Room
    host: !secret camera_living_room_ip
    username: !secret camera_living_room_username
    password: !secret camera_living_room_password
    stream: sub
    
  - platform: reolink_dev
    name: Bedroom
    host: !secret camera_bedroom_ip
    username: !secret camera_bedroom_username
    password: !secret camera_bedroom_password
    stream: sub

binary_sensor:
  - platform: template
    sensors:
      camera_front_door_motion:
        friendly_name: Front Door Camera Motion
        device_class: motion
        entity_id: camera.front_door
        value_template: "{{ is_state('camera.front_door', 'motion') }}"
        delay_off: 
            seconds: 10

  - platform: template
    sensors:
      camera_living_room_motion:
        friendly_name: Living Room Camera Motion
        device_class: motion
        entity_id: camera.living_room
        value_template: "{{ is_state('camera.living_room', 'motion') }}"
        delay_off: 
            seconds: 10

  - platform: template
    sensors:
      camera_bedroom_motion:
        friendly_name: Bedroom Camera Motion
        device_class: motion
        entity_id: camera.bedroom
        value_template: "{{ is_state('camera.bedroom', 'motion') }}"
        delay_off: 
            seconds: 10
