group:
  fridges:
    entities:
      - binary_sensor.fridge
      - binary_sensor.freezer
      - binary_sensor.big_freezer

  fridge_left_open_automations:
    entities:
      - automation.fridge_left_open
      - automation.fridge_left_open_reminder

  freezer_left_open_automations:
    entities:
      - automation.freezer_left_open
      - automation.freezer_left_open_reminder

  big_freezer_left_open_automations:
    entities:
      - automation.big_freezer_left_open
      - automation.big_freezer_left_open_reminder_10
      - automation.big_freezer_left_open_reminder_20

  all_fridge_automations:
    entities:
      - group.fridge_left_open_automations
      - group.freezer_left_open_automations
      - group.big_freezer_left_open_automations

automation:

  - alias: Fridge Left Open
    mode: single
    trigger:
    - platform: state
      entity_id: binary_sensor.fridge
      from: 'off'
      to: 'on'
      for: 
        minutes: 2
    action:
      - service: script.notify_all
        data:
          message: Hey, I think the fridge was left open
      - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.fridge
          from: 'on'
          to: 'off'
      - service: script.notify_all
        data:
          message: The fridge was closed

  - alias: Fridge Left Open Reminder
    mode: single
    trigger:
    - platform: state
      entity_id: binary_sensor.fridge
      from: 'off'
      to: 'on'
      for: 
        minutes: 10
    action:
      - service: script.notify_all
        data:
          message: The fridge is still open (10 minute reminder).

  - alias: Freezer Left Open
    mode: single
    trigger:
    - platform: state
      entity_id: binary_sensor.freezer
      from: 'off'
      to: 'on'
      for: 
        minutes: 2
    action:
      - service: script.notify_all
        data:
          message: Hey, I think the freezer was left open
      - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.freezer
          from: 'on'
          to: 'off'
      - service: script.notify_all
        data:
          message: The freezer was closed

  - alias: Freezer Left Open Reminder
    mode: single
    trigger:
    - platform: state
      entity_id: binary_sensor.freezer
      from: 'off'
      to: 'on'
      for: 
        minutes: 10
    action:
      - service: script.notify_all
        data:
          message: The freezer is still open (10 minute reminder).

  - alias: Big Freezer Left Open
    mode: single
    trigger:
    - platform: state
      entity_id: binary_sensor.big_freezer
      from: 'off'
      to: 'on'
      for: 
        minutes: 2
    action:
      - service: script.notify_all
        data:
          message: Hey, I think the big freezer was left open
      - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.big_freezer
          from: 'on'
          to: 'off'
      - service: script.notify_all
        data:
          message: The big freezer was closed

  - alias: Big Freezer Left Open Reminder 10
    mode: single
    trigger:
    - platform: state
      entity_id: binary_sensor.big_freezer
      from: 'off'
      to: 'on'
      for: 
        minutes: 10
    action:
      - service: script.notify_all
        data:
          message: The big freezer is still open (10 minute reminder).

  - alias: Big Freezer Left Open Reminder 20
    mode: single
    trigger:
    - platform: state
      entity_id: binary_sensor.big_freezer
      from: 'off'
      to: 'on'
      for: 
        minutes: 20
    action:
      - service: script.notify_all
        data:
          message: The big freezer is still open (20 minute reminder).

          