## Button 1: Sleep
## Button 2: Bedroom Curtain
## Button 3: Bedroom Shutter
## Button 4: Black Tablet


automation:
  - id: Hue Remote Riley Actions
    alias: Hue Remote Riley Actions
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.riley_hue_remote_action
    variables:
      button_code: "{{ trigger.to_state.state }}"
    action:
      - alias: "choose button"
        choose:
          ## Button 1 Short Click: White Tablet
          - conditions: "{{ button_code == 'on-press' }}"
            sequence:
              - service: switch.toggle
                entity_id: switch.house_tablet_screen

          ## Button Short Click: Volume On
          - conditions: "{{ button_code == 'up-press' }}"
            sequence:
              - service: input_number.set_value
                target:
                  entity_id: 
                    - input_number.house_tablet_volume
                    - input_number.black_tablet_volume
                data:
                  value: 5

          ## Button Short Click: Volume Off
          - conditions: "{{ button_code == 'down-press' }}"
            sequence:
              - service: input_number.set_value
                target:
                  entity_id: 
                    - input_number.house_tablet_volume
                    - input_number.black_tablet_volume
                data:
                  value: 0

          ## Button 4 Short Click: Black Tablet
          - conditions: "{{ button_code == 'off-press' }}"
            sequence:
              - service: switch.toggle
                entity_id: switch.black_tablet_screen
