## Button 1: Sleep
## Button 2: Fan
## Button 3: Shutter
## Button 4: Black Tablet

automation:
  - id: Bedroom Hue Remote Inbal Actions
    alias: Bedroom Hue Remote Inbal Actions
    mode: parallel
    trigger:
      - platform: state
        entity_id: sensor.inbal_hue_remote_action
        not_to: ''
    variables:
      button_code: "{{ trigger.to_state.state }}"
    action:
      - alias: "choose button"
        choose:
          ## Button 1 Release Hold: Sleep
          - conditions: "{{ button_code == 'on_hold' }}"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.sleep_scene

          ## Button 2 Release Short Press While Fan is Off: Turn On Fan
          - conditions: "{{ button_code == 'up_press_release' and is_state('fan.bedroom_fan', 'off') }}"
            sequence:
              - service: fan.turn_on
                entity_id: fan.bedroom_fan

          ## Button 2 Release Short Press While Fan is On: Cycle Fan Speed
          - conditions: "{{ button_code == 'up_press_release' and is_state('fan.bedroom_fan', 'on') }}"
            sequence:
              - service: fan.set_percentage
                data:
                  entity_id: fan.bedroom_fan
                  percentage: >-
                    {% set step = state_attr('fan.bedroom_fan', 'percentage_step') %}
                    {% set current = state_attr('fan.bedroom_fan', 'percentage') %}
                    {{ step if (current + step > 100) else (current + step) }}

          ## Button 2 Hold: Turn Off Fan
          - conditions: "{{ button_code == 'up_hold' }}"
            sequence:
              - service: fan.turn_off
                entity_id: fan.bedroom_fan

          ## Button 3 Release Short Press When in Motion: Stop Bedroom Shutter
          - conditions: "{{ button_code == 'down_press_release' and (is_state('cover.bedroom_shutter', 'opening') or is_state('cover.bedroom_shutter', 'closing')) }}"
            sequence:
              - service: cover.stop_cover
                entity_id: cover.bedroom_shutter

          ## Button 3 Release Short Press: Close Bedroom Shutter
          - conditions: "{{ button_code == 'down_press_release' }}"
            sequence:
              - service: cover.close_cover
                entity_id: cover.bedroom_shutter

          ## Button 3 Hold: Open Bedroom Shutter
          - conditions: "{{ button_code == 'down_hold' }}"
            sequence:
              - service: cover.open_cover
                entity_id: cover.bedroom_shutter

          ## Button 4 Short Press: Black Tablet
          - conditions: "{{ button_code == 'off_press' }}"
            sequence:
              - service: switch.toggle
                entity_id: switch.black_tablet_screen
