## Button 1: Sleep
## Button 2: Bedroom Curtain
## Button 3: Bedroom Shutter
## Button 4: Black Tablet

#com.mcu.reolink

automation:
  - id: Hue Remote Riley Actions
    alias: Hue Remote Riley Actions
    mode: parallel
    trigger:
      - platform: state
        entity_id: sensor.riley_hue_remote_action
        not_to: ''
    variables:
      button_code: "{{ trigger.to_state.state }}"
    action:
      - alias: "choose button"
        choose:
          ## Button 1 Short Click: Turn On White Tablet
          - conditions: "{{ button_code == 'on_press' }}"
            sequence:
              - service: switch.turn_on
                entity_id: switch.house_tablet_screen

              - if: 
                - condition: not
                  conditions:
                    - alias: "Foreground app isn't Reolink"
                      condition: state
                      entity_id: sensor.house_tablet_foreground_app
                      state: "com.mcu.reolink"
                then:
                  service: rest_command.house_tablet_run_reolink
                  
          ## Button Short Click: Volume On
          - conditions: "{{ button_code == 'up_press' }}"
            sequence:
              - service: input_number.set_value
                target:
                  entity_id:
                    - input_number.house_tablet_volume
                    - input_number.black_tablet_volume
                data:
                  value: 5

          ## Button Short Click: Volume Off
          - conditions: "{{ button_code == 'down_press' }}"
            sequence:
              - service: input_number.set_value
                target:
                  entity_id:
                    - input_number.house_tablet_volume
                    - input_number.black_tablet_volume
                data:
                  value: 0

          ## Button 4 Short Click: Turn Off White Tablet
          - conditions: "{{ button_code == 'off_press' }}"
            sequence:
              - service: switch.turn_off
                entity_id: switch.house_tablet_screen
