rest_command:
  open_sarters_parking_gate:
    url: !secret sarter_parking_gate_url
    method: "POST"
    payload: !secret sarter_parking_gate_payload
    timeout: 20

script:
  open_lower_gate_online:
    alias: Open Lower Gate Online
    sequence:
      - service: google_assistant_sdk.send_text_command
        data:
          command: "Open Lower Parking Gate"

  open_sarters_parking_gate_online:
    alias: Open Sarters Parking Gate Online
    sequence:
        - service: rest_command.open_sarters_parking_gate

automation:
- alias: Parking gates - Turn off remotes after 3 seconds
  mode: parallel
  trigger:
      - platform: state
        entity_id:
          - switch.lower_gate
          - switch.upper_gate
        from: 'off'
        to: 'on'
        for:
          seconds: 3
  action:
    - service: switch.turn_off
      data:
        entity_id: '{{ trigger.to_state.entity_id }}'

- alias: Parking gates - open lower gate online
  mode: parallel
  trigger:
      - platform: state
        entity_id:
          - switch.lower_gate
        from: 'off'
        to: 'on'
  action:
    - service: script.open_lower_gate_online