input_number:
  house_tablet_volume:
    name: Volume
    min: 0
    max: 10
    step: 1

  black_tablet_volume:
    name: Volume
    min: 0
    max: 10
    step: 1

rest_command:
  black_tablet_run_reolink:
    method: POST
    url: !secret black_tablet_rest_command_reolink_url

  house_tablet_run_reolink:
    method: POST
    url: !secret house_tablet_rest_command_reolink_url

script:
  toggle_tablet_volume:
    mode: parallel
    sequence: 
      - service: input_number.set_value
        target:
          entity_id: "{{ entity_id }}"
        data:
          value: "{{ default_value if states(entity_id) == '0' else 0 }}"

automation:
  - alias: Tablets change setting
    trigger:
      - platform: state
        entity_id: 
          - input_number.house_tablet_volume
          - input_number.black_tablet_volume

    variables:
      value: "{{ trigger.to_state.state | int / 10 }}"
      tablet_name: "{{ trigger.to_state.entity_id | replace('input_number.', '') | replace('_volume', '')  }}"

    action:
      - service: media_player.volume_set
        data:
          entity_id: "media_player.{{ tablet_name }}"
          volume_level: "{{ value }}"

  - alias: Tablets refresh when another language is selected
    trigger:
      - platform: state
        entity_id: 
          - input_select.local_lang_house_tablet
          - input_select.local_lang_black_tablet
    action:
      - service: button.press
        data:
          entity_id: "button.{{ trigger.to_state.entity_id | replace('input_select.local_lang_', '') }}_load_start_url"



  # - id: Control tablets from hue remote - power
  #   alias: Control tablets from hue remote - power
  #   mode: queued
  #   trigger:
  #     - platform: event
  #       event_type: deconz_event
  #       event_data:
  #         device_id: !secret philips_hue_remote_1_device_id
  #         event: 1000
  #     - platform: event
  #       event_type: deconz_event
  #       event_data:
  #         device_id: !secret philips_hue_remote_1_device_id
  #         event: 4000
  #   action:
  #     service: switch.toggle
  #     target:
  #       entity_id: 'switch.{{ trigger.event.data.event | regex_replace("100\d", "house_tablet") | regex_replace("400\d", "black_tablet") }}'

  # - id: Control tablets from hue remote - volume
  #   alias: Control tablets from hue remote - volume
  #   mode: queued
  #   trigger:
  #     - platform: event
  #       event_type:
  #         - deconz_event
  #       event_data:
  #         device_id: !secret philips_hue_remote_1_device_id
  #         event: 2000
  #     - platform: event
  #       event_type:
  #         - deconz_event
  #       event_data:
  #         device_id: !secret philips_hue_remote_1_device_id
  #         event: 3000
  #   action:
  #     - service: input_number.set_value
  #       target:
  #         entity_id: 
  #           - input_number.house_tablet_volume
  #           - input_number.black_tablet_volume
  #       data:
  #         value: "{{ trigger.event.data.event | replace('2000', '4') | replace('3000', '0') }}"