sensor:
  - platform: template
    sensors:
      bathroom_temperature:
        friendly_name: "Bathroom"
        unit_of_measurement: "°C"
        value_template: '{{ state_attr("sensor.cat_motion", "temperature") }}'

      living_room_temperature_monitor:
        friendly_name: Living Room Temperature
        value_template: >
          {% set temp = states('sensor.living_room_climate_temperature') | float %}
          {% set temp_max = states('input_number.room_temperature_max') | float %}
          {% set temp_min = states('input_number.room_temperature_min') | float %}
          {% if temp >= (temp_max + 1.5) %}
            Very Hot
          {% elif temp >= temp_max %}
            Hot
          {% elif temp <= temp_min - 1.5 %}
            Very Cold
          {% elif temp <= temp_min %}
            Cold
          {% else %}
            Ok
          {% endif %}


      office_temperature_monitor:
        friendly_name: Office Temperature
        value_template: >
          {% set temp = states('sensor.office_climate_temperature') | float %}
          {% set temp_max = states('input_number.room_temperature_max') | float %}
          {% set temp_min = states('input_number.room_temperature_min') | float %}
          {% if temp >= (temp_max + 1.5) %}
            Very Hot
          {% elif temp >= temp_max %}
            Hot
          {% elif temp <= temp_min - 1.5 %}
            Very Cold
          {% elif temp <= temp_min %}
            Cold
          {% else %}
            Ok
          {% endif %}


      guests_temperature_monitor:
        friendly_name: Guests Temperature
        value_template: >
          {% set temp = states('sensor.guests_climate_temperature') | float %}
          {% set temp_max = states('input_number.room_temperature_max') | float %}
          {% set temp_min = states('input_number.room_temperature_min') | float %}
          {% if temp >= (temp_max + 1.5) %}
            Very Hot
          {% elif temp >= temp_max %}
            Hot
          {% elif temp <= temp_min - 1.5 %}
            Very Cold
          {% elif temp <= temp_min %}
            Cold
          {% else %}
            Ok
          {% endif %}


      riley_temperature_monitor:
        friendly_name: Riley Temperature
        value_template: >
          {% set temp = states('sensor.riley_climate_temperature') | float %}
          {% set temp_max = states('input_number.room_temperature_max') | float %}
          {% set temp_min = states('input_number.room_temperature_min') | float %}
          {% if temp >= (temp_max + 1.5) %}
            Very Hot
          {% elif temp >= temp_max %}
            Hot
          {% elif temp <= temp_min - 1.5 %}
            Very Cold
          {% elif temp <= temp_min %}
            Cold
          {% else %}
            Ok
          {% endif %}


      bedroom_temperature_monitor:
        friendly_name: Bedroom Temperature
        value_template: >
          {% set temp = states('sensor.bedroom_climate_temperature') | float %}
          {% set temp_max = states('input_number.room_temperature_max') | float %}
          {% set temp_min = states('input_number.room_temperature_min') | float %}
          {% if temp >= (temp_max + 1.5) %}
            Very Hot
          {% elif temp >= temp_max %}
            Hot
          {% elif temp <= temp_min - 1.5 %}
            Very Cold
          {% elif temp <= temp_min %}
            Cold
          {% else %}
            Ok
          {% endif %}


      all_rooms_temperature_monitor:
        friendly_name: All Rooms Temperature
        value_template: >
          {{ states('sensor.living_room_temperature_monitor') if not is_state('sensor.living_room_temperature_monitor', 'Ok') else
             states('sensor.office_temperature_monitor') if not is_state('sensor.office_temperature_monitor', 'Ok') else
             states('sensor.guests_temperature_monitor') if not is_state('sensor.guests_temperature_monitor', 'Ok') else
             states('sensor.riley_temperature_monitor') if not is_state('sensor.riley_temperature_monitor', 'Ok') else
             states('sensor.bedroom_temperature_monitor') if not is_state('sensor.bedroom_temperature_monitor', 'Ok') else 'Ok' }}

input_select:
  season:
    options:
      - Summer
      - Autumn
      - Winter
      - Spring

input_number:
  room_temperature_max_summer:
    min: 15
    max: 32
    step: 0.1
    mode: box
  room_temperature_min_summer:
    min: 15
    max: 32
    step: 0.1
    mode: box
  room_temperature_max_autumn:
    min: 15
    max: 32
    step: 0.1
    mode: box
  room_temperature_min_autumn:
    min: 15
    max: 32
    step: 0.1
    mode: box
  room_temperature_max_winter:
    min: 15
    max: 32
    step: 0.1
    mode: box
  room_temperature_min_winter:
    min: 15
    max: 32
    step: 0.1
    mode: box
  room_temperature_max_spring:
    min: 15
    max: 32
    step: 0.1
    mode: box
  room_temperature_min_spring:
    min: 15
    max: 32
    step: 0.1
    mode: box
  room_temperature_max:
    min: 15
    max: 32
    step: 0.1
    mode: box
  room_temperature_min:
    min: 15
    max: 32
    step: 0.1
    mode: box

automation:
  - alias: Temperature Monitor Update Min Max Temp
    trigger:
      - platform: state
        entity_id:
          - input_number.room_temperature_min_summer
          - input_number.room_temperature_max_summer
          - input_number.room_temperature_min_autumn
          - input_number.room_temperature_max_autumn
          - input_number.room_temperature_min_winter
          - input_number.room_temperature_max_winter
          - input_number.room_temperature_min_spring
          - input_number.room_temperature_max_spring
          - input_select.season

    variables:
      season: "{{ states('input_select.season') }}"

    action:
      - service: input_number.set_value
        data:
          entity_id: input_number.room_temperature_max
          value: "{{ states('input_number.room_temperature_max_' + season) }}"

      - service: input_number.set_value
        data:
          entity_id: input_number.room_temperature_min
          value: "{{ states('input_number.room_temperature_min_' + season) }}"
