sensor:
  - platform: template
    sensors:
      bathroom_temperature:
        friendly_name: "Bathroom"
        unit_of_measurement: '°C'
        value_template: '{{ state_attr("sensor.cat_motion", "temperature") }}'

  - platform: template
    sensors:
      outside_temperature:
        friendly_name: "Outside Temperature"
        unit_of_measurement: '°C'
        value_template: '{{ state_attr("binary_sensor.rain", "temperature") }}'