#This was moved to UI
# apcupsd:
#   host: !secret apcupsd_ip

sensor:

  #This was moved to UI
#   - platform: apcupsd
#     resources:
#       - bcharge
#       - status
#       - tonbatt
#       - loadpct
#       - timeleft
#       - numxfers

  - platform: template
    sensors:
      power_outage_today:
        friendly_name: "Was there a power outage today?"
        value_template: "{{ (states('input_number.power_outages_today_count') | int) > 0 }}"

input_datetime:
  last_power_outage:
    name: Last Power Outage
    has_date: true
    has_time: true

input_number:
  power_outages_today_count:
    name: Power Outages Today
    min: 0
    max: 100
    step: 1
    mode: box

  power_outages_monthly_count:
    name: Power Outages Monthly
    min: 0
    max: 100
    step: 1
    mode: box

automation:
  - alias: Power - Save Last Outage Time
    trigger:
      - platform: state
        entity_id: sensor.ups_transfer_count
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: sensor.ups_transfer_count
          state: "0"
        - condition: state
          entity_id: sensor.ups_transfer_count
          state: "unavailable"
    action:
      - service: input_datetime.set_datetime
        data:
          entity_id: input_datetime.last_power_outage
          datetime: '{{ now() }}'
      - service: input_number.increment
        target:
          entity_id: 
            - input_number.power_outages_today_count
            - input_number.power_outages_monthly_count

  - alias: Power - Reset outages counter
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      service: input_number.set_value
      data:
        value: 0
      target:
        entity_id: input_number.power_outages_today_count


  - alias: Power - Reset monthly counter & notify
    trigger:
      - platform: time
        at: "00:00:01"
    condition:
      condition: template
      value_template: "{{ now().day == 1 }}"
    action:
      - service: notify.shlomi
        data:
          message: "Monthly power outages report: {{ states('input_number.power_outages_monthly_count') | int }} outages"
      - service: input_number.set_value
        data:
          value: 0
        target:
          entity_id: input_number.power_outages_monthly_count

  - alias: Power - notify on power outage
    trigger:
      - platform: state
        entity_id: sensor.ups_status
        from: "ONLINE"
        to: "ONBATT"
        id: "outage"

      - platform: state
        entity_id: sensor.ups_status
        from: "ONBATT"
        to: "ONLINE"
        id: "normal_power"

    action:
      - service: notify.shlomi
        data:
          message: |
            {% if trigger.id == "outage" %}
              Power outage at home, running on UPS! Battery: {{ states('sensor.ups_battery') }}
            {% elif trigger.id == "normal_power" %}
              Power has returned! Battery: {{ states('sensor.ups_battery') }}
            {% endif %}
