apcupsd:
  host: !secret apcupsd_ip

sensor:
  - platform: apcupsd
    resources:
      - bcharge
      - status
      - tonbatt
      - loadpct
      - timeleft
      - numxfers

  - platform: template
    sensors:
      power_outage_today:
        friendly_name: "Was there a power outage today?"
        value_template: "{{ state_attr('input_datetime.last_power_outage', 'timestamp') | timestamp_custom('%Y-%m-%d') == now().strftime('%Y-%m-%d') }}"

input_datetime:
  last_power_outage:
    name: Last Power Outage
    has_date: true
    has_time: true

automation:
  - alias: Power - Save Last Outage Time
    trigger:
      - platform: state
        entity_id: sensor.ups_transfer_count
    condition:
      condition: not
      conditions:
        - condition: state
          entity_id: sensor.ups_transfer_count
          state: "0"
        - condition: state
          entity_id: sensor.ups_transfer_count
          state: "unavailable"
    action:
      service: input_datetime.set_datetime
      data:
        entity_id: input_datetime.last_power_outage
        datetime: '{{ now() }}'


