switcher_kis:
  phone_id: !secret switcher_phone_id
  device_id: !secret switcher_device_id
  device_password: !secret switcher_device_password

input_datetime:
  water_boiler_last_on:
    has_date: true
    has_time: true
  water_boiler_last_off:
    has_date: true
    has_time: true

automation:
  - id: Save Water Boiler On Off Time
    alias: Save Water Boiler On Off Time
    trigger:
      - platform: state
        entity_id: switch.water_boiler
        from: "on"
        to: "off"
      - platform: state
        entity_id: switch.water_boiler
        from: "off"
        to: "on"
    action:
      service: input_datetime.set_datetime
      data:
        entity_id: "input_datetime.water_boiler_last_{{ trigger.to_state.state }}"
        datetime: "{{ now() }}"

sensor:
  - platform: history_stats
    name: Water Boiler Metrics Duration Today
    entity_id: switch.water_boiler
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: template
    sensors:
      water_boiler_metrics_duration_last_time:
        friendly_name: "Water Boiler Metrics Duration Last Time"
        value_template: >
          {% if is_state('switch.water_boiler', 'on') %}
          {{ as_datetime(as_timestamp(now()) - state_attr('input_datetime.water_boiler_last_on', 'timestamp')).strftime('%-Hh %-Mm')  | replace('0h ', '') | replace('0m', '') }}
          {% else %}
          {{ as_datetime(state_attr('input_datetime.water_boiler_last_off', 'timestamp') - state_attr('input_datetime.water_boiler_last_on', 'timestamp')).strftime('%-Hh %-Mm')  | replace('0h ', '') | replace('0m', '') }}
          {% endif %}
          

  - platform: template
    sensors:
      water_boiler_metrics_time_since_finished:
        friendly_name: "Water Boiler Metrics Time Since Finished"
        value_template: "{{ as_datetime(as_timestamp(now()) - state_attr('input_datetime.water_boiler_last_off', 'timestamp')).strftime('%-Hh %-Mm')  | replace('0h ', '') | replace('0m', '') }}"

