input_boolean:
  living_room_script_running:
  guests_script_running:
  riley_script_running:
  bedroom_main_light:

  living_room_color_fix:
  guests_main_color_fix:
  riley_main_color_fix:

input_number:
  living_room_light_level:
    min: 0
    max: 18
    step: 1
  guests_light_level:
    min: 0
    max: 18
    step: 1
  riley_light_level:
    min: 0
    max: 18
    step: 1

light:

  - platform: template
    lights:
      living_room_entrance:
        unique_id: "Living Room Light Entrance"
        friendly_name: "Living Room Entrance"
        value_template: "{{ is_state('switch.living_room_entrance','on') }}"
        level_template: "{{ (states.input_number.living_room_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('switch.living_room_entrance','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: switch.living_room_entrance
        turn_off:
          - service: homeassistant.turn_off
            entity_id: switch.living_room_entrance
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: living_room
              new_brightness_level: "{{ brightness }}"

  - platform: template
    lights:
      living_room_hallway:
        unique_id: "Living Room Light Hallway"
        friendly_name: "Living Room Hallway"
        value_template: "{{ is_state('switch.living_room_hallway','on') }}"
        level_template: "{{ (states.input_number.living_room_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('switch.living_room_hallway','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: switch.living_room_hallway
        turn_off:
          - service: homeassistant.turn_off
            entity_id: switch.living_room_hallway
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: living_room
              new_brightness_level: "{{ brightness }}"

  - platform: template
    lights:
      guests_main:
        unique_id: "Guests Light Main"
        friendly_name: "Guests Main"
        value_template: "{{ is_state('switch.guests_main','on') }}"
        level_template: "{{ (states.input_number.guests_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('switch.guests_main','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: switch.guests_main
        turn_off:
          - service: homeassistant.turn_off
            entity_id: switch.guests_main
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: guests
              new_brightness_level: "{{ brightness }}"

  - platform: template
    lights:
      riley_main:
        unique_id: "Riley Light Main"
        friendly_name: "Riley Main"
        value_template: "{{ is_state('switch.riley_main','on') }}"
        level_template: "{{ (states.input_number.riley_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('switch.riley_main','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: switch.riley_main
        turn_off:
          - service: homeassistant.turn_off
            entity_id: switch.riley_main
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: riley
              new_brightness_level: "{{ brightness }}"

  - platform: template
    lights:
      bedroom_entrance:
        unique_id: "Bedroom Light Entrance"
        friendly_name: "Bedroom Entrance"
        value_template: "{{ is_state('switch.bedroom_entrance','on') }}"
        level_template: "{% set level = state_attr('light.bedroom_entrance_hue','brightness') %}{{ level if level != None else 0 }}"
        availability_template: "{{ not is_state('switch.bedroom_entrance','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: switch.bedroom_entrance
        turn_off:
          - service: homeassistant.turn_off
            entity_id: switch.bedroom_entrance
        set_level:
          - service: light.turn_on
            data:
              entity_id: light.bedroom_entrance_hue
              brightness: "{{ brightness }}"


  - platform: template
    lights:
      kitchen_island:
        unique_id: "Kitchen Light Island"
        friendly_name: "Kitchen Island"
        value_template: "{{ is_state('switch.kitchen_island','on') }}"
        level_template: "{% set level = state_attr('light.kitchen_island_1','brightness') %}{{ level if level != None else 0 }}"
        availability_template: "{{ not is_state('switch.kitchen_island','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: switch.kitchen_island
        turn_off:
          - service: homeassistant.turn_off
            entity_id: switch.kitchen_island
        set_level:
          - service: light.turn_on
            data:
              entity_id: light.kitchen_island_1
              brightness: "{{ brightness }}"
          - service: light.turn_on
            data:
              entity_id: light.kitchen_island_2
              brightness: "{{ brightness }}"
          - service: light.turn_on
            data:
              entity_id: light.kitchen_island_3
              brightness: "{{ brightness }}"

  # - platform: template
  #   lights:
  #     living_room_side_lamp:
  #       unique_id: "Living Room Light Side Lamp"
  #       friendly_name: "Living Room Side Lamp"
  #       value_template: "{{ is_state('light.living_room_side_lamp_hue','on') }}"
  #       level_template: "{{ state_attr('light.living_room_side_lamp_hue','brightness') }}"
  #       availability_template: "{{ not (is_state('switch.living_room_side_lamp_smart_plug','unavailable') and is_state('light.living_room_side_lamp_hue','unavailable')) }}" #If smart plug and hue are both unavailable, then unavailable. Otherwise, available.
  #       turn_on:
  #         - service: homeassistant.turn_on
  #           entity_id: light.living_room_side_lamp_hue
  #       turn_off:
  #         - service: light.turn_off
  #           entity_id: light.living_room_side_lamp_hue
  #       set_level:
  #         - service: light.turn_on
  #           data:
  #             entity_id: light.living_room_side_lamp_hue
  #             brightness: "{{ brightness }}"

group:
  living room color changing lights:
    entities:
      - light.living_room_entrance
      - light.living_room_hallway

automation:
  - alias: Living Room Light Color Fix Check
    description: ""
    trigger:
      - platform: state
        entity_id: group.living_room_color_changing_lights
        from: "on"
        to: "off"
        for: "20"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.living_room_color_fix

  - alias: Living Room Light Color Fix
    description: ""
    trigger:
      - platform: state
        entity_id: group.living_room_color_changing_lights
        from: "off"
        to: "on"
        for: "5"
    condition:
      condition: state
      entity_id: input_boolean.living_room_color_fix
      state: "on"
    action:
      - service: script.ceiling_light_color_change2
        data:
          room: living_room
      - service: input_boolean.turn_off
        entity_id: input_boolean.living_room_color_fix

  - alias: Guests Light Color Fix Check
    description: ""
    trigger:
      - platform: state
        entity_id: switch.guests_main
        to: "off"
        for: "60"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guests_main_color_fix

  - alias: Guests Light Color Fix
    description: ""
    trigger:
      - platform: state
        entity_id: switch.guests_main
        from: "off"
        to: "on"
        for: "1"
    condition:
      condition: state
      entity_id: input_boolean.guests_main_color_fix
      state: "on"
    action:
      - service: script.ceiling_light_color_change3
        data:
          room: guests
      - service: input_boolean.turn_off
        entity_id: input_boolean.guests_main_color_fix

  - alias: Riley Light Color Fix Check
    description: ""
    trigger:
      - platform: state
        entity_id: switch.riley_main
        to: "off"
        for: "60"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.riley_main_color_fix

  - alias: Riley Light Color Fix
    description: ""
    trigger:
      - platform: state
        entity_id: switch.riley_main
        from: "off"
        to: "on"
        for: "1"
    condition:
      condition: state
      entity_id: input_boolean.riley_main_color_fix
      state: "on"
    action:
      - service: script.ceiling_light_color_change3
        data:
          room: riley
      - service: input_boolean.turn_off
        entity_id: input_boolean.riley_main_color_fix

  - alias: Ceiling Lights Set Full Brightness When Turning On
    id: Ceiling Lights Set Full Brightness When Turning On
    trigger:
      - platform: state
        entity_id:
          - switch.living_room_entrance
          - switch.living_room_hallway
          - switch.living_room_main
          - switch.guests_main
          - switch.riley_main
        from: "off"
        to: "on"
    action:
      - service: input_number.set_value
        data:
          entity_id: "input_number.{{ trigger.to_state.entity_id | replace('switch.', '') | replace('_entrance', '') | replace('_hallway', '')  | replace('main_', '') | replace('_main', '') }}_light_level"
          value: 18

