input_boolean:
  living_room_script_running:
  office_script_running:
  birds_script_running:
  riley_script_running:

  living_room_color_fix:
  office_main_color_fix:
  birds_main_color_fix:
  riley_main_color_fix:

input_number:
  living_room_light_level:
    min: 0
    max: 18
    step: 1
  office_light_level:
    min: 0
    max: 18
    step: 1
  birds_light_level:
    min: 0
    max: 18
    step: 1
  riley_light_level:
    min: 0
    max: 18
    step: 1

light:
  - platform: template
    lights:
      living_room_main_combined:
        unique_id: "Living Room Light Main"
        friendly_name: "Living Room Main Dimmable"
        value_template: "{{ is_state('light.living_room_main','on') }}"
        level_template: "{{ (states.input_number.living_room_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('light.living_room_main','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.living_room_main
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.living_room_main
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: living_room
              new_brightness_level: "{{ brightness }}"

  - platform: template
    lights:
      living_room_entrance_combined:
        unique_id: "Living Room Light Entrance"
        friendly_name: "Living Room Entrance Dimmable"
        value_template: "{{ is_state('light.living_room_entrance','on') }}"
        level_template: "{{ (states.input_number.living_room_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('light.living_room_entrance','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.living_room_entrance
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.living_room_entrance
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: living_room
              new_brightness_level: "{{ brightness }}"

  - platform: template
    lights:
      living_room_hallway_combined:
        unique_id: "Living Room Light Hallway"
        friendly_name: "Living Room Hallway Dimmable"
        value_template: "{{ is_state('light.living_room_hallway','on') }}"
        level_template: "{{ (states.input_number.living_room_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('light.living_room_hallway','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.living_room_hallway
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.living_room_hallway
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: living_room
              new_brightness_level: "{{ brightness }}"

  # - platform: template
  #   lights:
  #     hallway_main_combined:
  #       friendly_name: "Hallway Main Dimmable"
  #       value_template: "{{ is_state('light.hallway_main','on') }}"
  #       level_template: "{{ max((expand('group.hallway_lights') | selectattr('state', 'equalto', 'on') | map(attribute='attributes.brightness') | list) or [0]) }} "
  #       availability_template: "{{ not is_state('light.hallway_main','unavailable') }}"
  #       turn_on:
  #         - service: homeassistant.turn_on
  #           entity_id: light.hallway_main
  #       turn_off:
  #         - service: homeassistant.turn_off
  #           entity_id: light.hallway_main
  #       set_level:
  #         - service: light.turn_on
  #           entity_id: light.hallway_main
  #         - wait_template: "{{ is_state('light.hallway_dimmable_lights', 'on') }}"
  #           timeout:
  #             seconds: 2
  #         - service: light.turn_on
  #           data:
  #             entity_id: light.hallway_dimmable_lights
  #             brightness: "{{ brightness }}"


  - platform: template
    lights:
      hallway_main_combined:
        unique_id: "Hallway Main Dimmable"
        friendly_name: "Hallway Main Dimmable"
        value_template: "{{ is_state('light.hallway_controllers_group','on') }}"
        level_template: "{{ state_attr('light.hallway_controllers_group','brightness') }}"
        availability_template: "{{ not (is_state('light.hallway_front','unavailable') and is_state('light.hallway_back','unavailable')) }}" #If hallway front & back are both unavailable, then unavailable. Otherwise, available.
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.hallway_controllers_group
        turn_off:
          - service: light.turn_off
            entity_id: light.hallway_controllers_group
        set_level:
          - service: light.turn_on
            data:
              entity_id: light.hallway_controllers_group
              brightness: "{{ brightness }}"

  - platform: template
    lights:
      living_room_tv_light_combined:
        unique_id: "Living Room Light TV Light"
        friendly_name: "Living Room TV Light Dimmable"
        value_template: "{{ is_state('light.living_room_tv_light','on') }}"
        level_template: "{{ state_attr('light.living_room_tv_light_dimmer','brightness') }}"
        availability_template: "{{ not is_state('light.living_room_tv_light','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.living_room_tv_light
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.living_room_tv_light
        set_level:
          - service: light.turn_on
            entity_id: light.living_room_tv_light
          - wait_template: "{{ is_state('light.living_room_tv_light_dimmer', 'on') }}"
            timeout:
              seconds: 2
          - service: light.turn_on
            data:
              entity_id: light.living_room_tv_light_dimmer
              brightness: "{{ brightness }}"

  - platform: template
    lights:
      living_room_tv_light_combined:
        friendly_name: "Hallway Main Dimmable"
        value_template: "{{ is_state('light.hallway_main','on') }}"
        level_template: "{{ state_attr('light.living_room_tv_light_dimmer','brightness') }}"
        availability_template: "{{ not is_state('light.living_room_tv_light','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.living_room_tv_light
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.living_room_tv_light
        set_level:
          - service: light.turn_on
            data:
              entity_id:
                - light.living_room_tv_light
                - light.living_room_tv_light_dimmer
              brightness: "{{ brightness }}"

  - platform: template
    lights:
      office_main_combined:
        friendly_name: "Office Main Dimmable"
        value_template: "{{ is_state('light.office_main','on') }}"
        level_template: "{{ (states.input_number.office_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('light.office_main','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.office_main
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.office_main
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: office
              new_brightness_level: "{{ brightness }}"
        set_temperature:
          service: script.ceiling_light_color_change
          data:
            room: office

  - platform: template
    lights:
      birds_main_combined:
        friendly_name: "Birds Main Dimmable"
        value_template: "{{ is_state('light.birds_main','on') }}"
        level_template: "{{ (states.input_number.birds_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('light.birds_main','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.birds_main
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.birds_main
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: birds
              new_brightness_level: "{{ brightness }}"

  - platform: template
    lights:
      riley_main_combined:
        friendly_name: "Riley Main Dimmable"
        value_template: "{{ is_state('light.riley_main','on') }}"
        level_template: "{{ (states.input_number.riley_light_level.state|int * 14.166)|round }}"
        availability_template: "{{ not is_state('light.riley_main','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.riley_main
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.riley_main
        set_level:
          - service: python_script.ceiling_light_set_level
            data:
              room: riley
              new_brightness_level: "{{ brightness }}"

  - platform: template
    lights:
      bedroom_entrance_combined:
        friendly_name: "Bedroom Entrance Dimmable"
        value_template: "{{ is_state('light.bedroom_entrance','on') }}"
        level_template: "{% set level = state_attr('light.bedroom_entrance_hue','brightness') %}{{ level if level != None else 0 }}"
        availability_template: "{{ not is_state('light.bedroom_entrance','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.bedroom_entrance
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.bedroom_entrance
        set_level:
          - service: light.turn_on
            data:
              entity_id: light.bedroom_entrance_hue
              brightness: "{{ brightness }}"

  - platform: template
    lights:
      bedroom_main_combined:
        friendly_name: "Bedroom Main Dimmable"
        value_template: "{{ is_state('light.bedroom_main','on') }}"
        level_template: "{% set level = state_attr('light.bedroom_main_hue','brightness') %}{{ level if level != None else 0 }}"
        availability_template: "{{ not is_state('light.bedroom_main','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.bedroom_main
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.bedroom_main
        set_level:
          - service: light.turn_on
            data:
              entity_id: light.bedroom_main_hue
              brightness: "{{ brightness }}"

  - platform: template
    lights:
      kitchen_island_combined:
        friendly_name: "Kitchen Island Dimmable"
        value_template: "{{ is_state('light.kitchen_island','on') }}"
        level_template: "{% set level = state_attr('light.kitchen_island_1','brightness') %}{{ level if level != None else 0 }}"
        availability_template: "{{ not is_state('light.kitchen_island','unavailable') }}"
        turn_on:
          - service: homeassistant.turn_on
            entity_id: light.kitchen_island
        turn_off:
          - service: homeassistant.turn_off
            entity_id: light.kitchen_island
        set_level:
          - service: light.turn_on
            data:
              entity_id: light.kitchen_island_1
              brightness: "{{ brightness }}"
          - service: light.turn_on
            data:
              entity_id: light.kitchen_island_2
              brightness: "{{ brightness }}"
          - service: light.turn_on
            data:
              entity_id: light.kitchen_island_3
              brightness: "{{ brightness }}"

  - platform: template
    lights:
      living_room_side_lamp_combined:
        unique_id: "Living Room Light Side Lamp"
        friendly_name: "Living Room Side Lamp Dimmable"
        value_template: "{{ is_state('light.living_room_side_lamp_hue','on') }}"
        level_template: "{{ state_attr('light.living_room_side_lamp_hue','brightness') }}"
        availability_template: "{{ not (is_state('switch.living_room_side_lamp_smart_plug','unavailable') and is_state('light.living_room_side_lamp_hue','unavailable')) }}" #If smart plug and hue are both unavailable, then unavailable. Otherwise, available.
        turn_on:
          - service: homeassistant.turn_on
            entity_id:
              - switch.living_room_side_lamp_smart_plug
              - light.living_room_side_lamp_hue
        turn_off:
          - service: light.turn_off
            entity_id: light.living_room_side_lamp_hue
        set_level:
          - service: light.turn_on
            data:
              entity_id: light.living_room_side_lamp_hue
              brightness: "{{ brightness }}"

group:
  living room dimmable lights:
    entities:
      - light.living_room_main_combined
      - light.living_room_entrance_combined
      - light.living_room_hallway_combined

automation:
  - alias: Living Room Light Color Fix Check
    description: ""
    trigger:
      - platform: state
        entity_id: group.living_room_dimmable_lights
        from: "on"
        to: "off"
        for: "20"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.living_room_color_fix

  - alias: Living Room Light Color Fix
    description: ""
    trigger:
      - platform: state
        entity_id: group.living_room_dimmable_lights
        from: "off"
        to: "on"
        for: "5"
    condition:
      condition: state
      entity_id: input_boolean.living_room_color_fix
      state: "on"
    action:
      - service: script.ceiling_light_color_change2
        data:
          room: living_room
      - service: input_boolean.turn_off
        entity_id: input_boolean.living_room_color_fix

  - alias: Office Light Color Fix Check
    description: ""
    trigger:
      - platform: state
        entity_id: light.office_main
        to: "off"
        for: "60"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.office_main_color_fix

  - alias: Office Light Color Fix
    description: ""
    trigger:
      - platform: state
        entity_id: light.office_main
        from: "off"
        to: "on"
        for: "1"
    condition:
      condition: state
      entity_id: input_boolean.office_main_color_fix
      state: "on"
    action:
      - service: script.ceiling_light_color_change3
        data:
          room: office
      - service: input_boolean.turn_off
        entity_id: input_boolean.office_main_color_fix

  - alias: Birds Light Color Fix Check
    description: ""
    trigger:
      - platform: state
        entity_id: light.birds_main
        to: "off"
        for: "60"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.birds_main_color_fix

  - alias: Birds Light Color Fix
    description: ""
    trigger:
      - platform: state
        entity_id: light.birds_main
        from: "off"
        to: "on"
        for: "1"
    condition:
      condition: state
      entity_id: input_boolean.birds_main_color_fix
      state: "on"
    action:
      - service: script.ceiling_light_color_change3
        data:
          room: birds
      - service: input_boolean.turn_off
        entity_id: input_boolean.birds_main_color_fix

  - alias: Riley Light Color Fix Check
    description: ""
    trigger:
      - platform: state
        entity_id: light.riley_main
        to: "off"
        for: "60"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.riley_main_color_fix

  - alias: Riley Light Color Fix
    description: ""
    trigger:
      - platform: state
        entity_id: light.riley_main
        from: "off"
        to: "on"
        for: "1"
    condition:
      condition: state
      entity_id: input_boolean.riley_main_color_fix
      state: "on"
    action:
      - service: script.ceiling_light_color_change3
        data:
          room: riley
      - service: input_boolean.turn_off
        entity_id: input_boolean.riley_main_color_fix

  - alias: Ceiling Lights Set Full Brightness When Turning On
    description: ""
    trigger:
      - platform: state
        entity_id:
          - light.living_room_entrance
          - light.living_room_hallway
          - light.living_room_main
          - light.office_main
          - light.birds_main
          - light.riley_main
        from: "off"
        to: "on"
    action:
      - service: python_script.ceiling_light_set_level_when_turning_on
        data:
          entity_id: "{{ trigger.to_state.entity_id }}"
