group:
  hallway_toggles:
    all: true
    entities:
      - switch.hallway_toggle_back
      - switch.hallway_toggle_front

automation:
  - alias: Living room sync fan light
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - light.living_room_main
          - light.living_room_ceiling_fan
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.living_room_main
          - light.living_room_ceiling_fan

  - alias: Living room sync side lamp
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - light.living_room_side_lamp
          - switch.living_room_side_lamp_toggle
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.living_room_side_lamp
          - switch.living_room_side_lamp_toggle

  - alias: Living room tv light sync dimmer
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.living_room_tv_light_toggle
          - light.living_room_tv_light
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - switch.living_room_tv_light_toggle
          - light.living_room_tv_light

  - alias: Stairs switch sync
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.stairs_toggle
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: switch.stairs

  - alias: Balcony sync fan light with main light
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - light.balcony_main
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.balcony_fan
          - light.balcony_main
          

  - alias: Office switches sync bff light
    id: Office switches sync bff light
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - light.office_bff_light
          - switch.office_bff_light_toggle
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.office_bff_light
          - switch.office_bff_light_toggle

  - alias: Riley toggle sync main light
    id: Riley toggle sync main light
    max_exceeded: silent
    mode: single
    trigger:
      #Riley's toggle button was pressed
      - platform: state
        entity_id: sensor.riley_main_toggle
        not_from:
          - unavailable
          - unknown
        to:
          - single
          - double
          - long
    condition:
      - condition: or
        conditions:
          #Allow using the button only when Riley isn't sleeping
          - alias: "Riley isn't sleeping"
            condition: state
            entity_id: input_boolean.riley_is_sleeping
            state: "off"

          #Or when Riley is sleeping, but the light is on (and she would like to turn it off)
          - condition: and
            conditions:
              - alias: "Riley is sleeping"
                condition: state
                entity_id: input_boolean.riley_is_sleeping
                state: "on"
              - alias: "The light is on"
                condition: state
                entity_id: light.riley_main
                state: "on"

    action:
      - service: light.toggle
        entity_id: light.riley_main

  - alias: Guests switches sync main
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.guests_main
          - switch.guests_main_toggle
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - switch.guests_main
          - switch.guests_main_toggle

  - alias: Bathroom cabinet sync
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - light.bathroom_cabinet
          - switch.bathroom_cabinet_toggle
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.bathroom_cabinet_group

  - alias: Hallway sync switches when controllers change
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id: light.hallway_controllers_group
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown

    condition: #This is needed to avoid endless loops
      - alias: "Hallway main group is not the same state"
        condition: template
        value_template: "{{ not is_state('group.hallway_toggles', trigger.to_state.state) }}"

    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: group.hallway_toggles

  - alias: Hallway sync controllers when switches change
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.hallway_toggle_front
          - switch.hallway_toggle_back
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown

    condition: #This is needed to avoid endless loops
      - alias: "Hallway controller group is not the same state"
        condition: template
        value_template: "{{ not is_state('light.hallway_controllers_group', trigger.to_state.state) }}"

    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.hallway_controllers_group
          - group.hallway_toggles

  - alias: Riley switches scene
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.riley_scene_toggle
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: light.turn_on
        entity_id:
          - light.riley_main
        data:
          brightness: "{{ 255 if state_attr('light.riley_main', 'brightness')|int < 127 else 1 }}"

  - alias: Bedroom switches sync main
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.bedroom_main_toggle_left
          - switch.bedroom_main_toggle_right
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: light.toggle
        entity_id: light.bedroom_main

  - alias: Bedroom switches sync entrance
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.bedroom_entrance_toggle_left
          - switch.bedroom_entrance_toggle_right
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: light.toggle
        entity_id: light.bedroom_entrance

  - alias: Bedroom fan toggles
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - switch.bedroom_fan_toggle
          - switch.bedroom_fan_toggle_left
          - switch.bedroom_fan_toggle_right
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: fan.toggle
        entity_id: fan.bedroom_fan

  - alias: Balcony fan sync switch
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - fan.balcony_fan
          - switch.balcony_fan_toggle
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: group.balcony_fan_group

  - alias: Balcony string lights sync switch
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - light.balcony_string_lights
          - switch.balcony_string_lights_toggle
        not_from:
          - unavailable
          - unknown
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.balcony_string_lights
          - switch.balcony_string_lights_toggle
