automation:
  - alias: Living room sync side lamp
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.living_room_side_lamp_hue
          - switch.living_room_side_lamp_toggle
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.living_room_side_lamp_combined
          - switch.living_room_side_lamp_toggle

  - alias: Living room tv light sync dimmer
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - switch.living_room_tv_light
          - light.living_room_tv_light_dimmer
        not_from: "unavailable"
        not_to: "unavailable"

    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.living_room_tv_light_group

  - alias: Stairs switch sync
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.stairs
          - switch.stairs_module
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: light.stairs_group

  - alias: Office switches sync bff light
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.office_bff_light
          - light.office_bff_light_toggle
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: light.office_bff_light_group

  - alias: Guests switches sync main
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.guests_main
          - light.guests_main_toggle
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: light.guests_main_group

  - alias: Bathroom cabinet sync
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.bathroom_cabinet
          - light.bathroom_cabinet_toggle
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: light.bathroom_cabinet_group

  # - alias: Hallway switches sync main
  #   max_exceeded: silent
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - light.hallway_main
  #         - light.hallway_main_toggle
  #   condition:
  #     condition: not
  #     conditions:
  #       - condition: state
  #         entity_id:
  #           - light.hallway_main
  #           - light.hallway_main_toggle
  #         state: "unavailable"
  #   action:
  #     - service: "homeassistant.turn_{{ trigger.to_state.state }}"
  #       entity_id: light.hallway_main_group

  - alias: Hallway sync switches when controllers change
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id: light.hallway_controllers_group
        not_from: "unavailable"
        not_to: "unavailable"

    condition: #This is needed to avoid endless loops
      - alias: "Hallway main group is not the same state"
        condition: template
        value_template: "{{ not is_state('light.hallway_main_group', trigger.to_state.state) }}"

    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: light.hallway_main_group

  - alias: Hallway sync controllers when switches change
    max_exceeded: silent
    mode: single
    trigger:
      - platform: state
        entity_id:
          - light.hallway_main
          - light.hallway_main_toggle
        not_from: "unavailable"
        not_to: "unavailable"

    condition: #This is needed to avoid endless loops
      - alias: "Hallway controller group is not the same state"
        condition: template
        value_template: "{{ not is_state('light.hallway_controllers_group', trigger.to_state.state) }}"

    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id:
          - light.hallway_controllers_group
          - light.hallway_main_group

  - alias: Riley switches scene
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.riley_scene_toggle
        not_to:
          - unavailable
          - unknown
    action:
      - service: light.turn_on
        entity_id:
          - light.riley_main_combined
        data:
          brightness: '{{ 255 if ( (state_attr("light.riley_main_combined", "brightness") or state_attr("light.riley_main_combined", "brightness")) < 127) else 1 }}'

  - alias: Bedroom switches sync main
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.bedroom_main
          - light.bedroom_main_toggle_left
          - light.bedroom_main_toggle_right
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: light.bedroom_main_group

  - alias: Bedroom switches sync entrance
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.bedroom_entrance
          - light.bedroom_entrance_toggle_left
          - light.bedroom_entrance_toggle_right
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: light.bedroom_entrance_group

  - alias: Bedroom switches scene
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.bedroom_scene
          - light.bedroom_scene_left
          - light.bedroom_scene_right
        not_to:
          - unavailable
          - unknown
    action:
      - service: light.turn_on
        entity_id: light.bedroom_dimmable_lights
        data:
          brightness: "{{ 255 if state_attr('light.bedroom_dimmable_lights', 'brightness')|int < 127 else 1 }}"

  # - alias: Living room switches scene
  #   trigger:
  #     - platform: state
  #       entity_id: light.living_room_scene
  #   condition:
  #     condition: not
  #     conditions:
  #         - condition: state
  #           entity_id: light.living_room_scene
  #           state: 'unavailable'
  #   action:
  #     - service: script.ceiling_light_color_change
  #       data:
  #         room: living_room

  - alias: Balcony fan sync switch
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - fan.balcony_fan
          - switch.balcony_fan_toggle
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: group.balcony_fan_group

  - alias: Balcony string lights sync switch
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id:
          - light.balcony_string_lights
          - light.balcony_string_lights_toggle
        not_to:
          - unavailable
          - unknown
    action:
      - service: "homeassistant.turn_{{ trigger.to_state.state }}"
        entity_id: light.balcony_string_lights_group
